rfmix -f ../rfmix4/Nakanai-Mangseng.chr1.vcf.gz -r ../rfmix4/bisnp.chr1.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr1.txt -m ../rfmix4/Ref.map --chromosome=1 -o Nakanai-Mangseng.chr1 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Nakanai-Mangseng.chr2.vcf.gz -r ../rfmix4/bisnp.chr2.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr2.txt -m ../rfmix4/Ref.map --chromosome=2 -o Nakanai-Mangseng.chr2 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Nakanai-Mangseng.chr3.vcf.gz -r ../rfmix4/bisnp.chr3.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr3.txt -m ../rfmix4/Ref.map --chromosome=3 -o Nakanai-Mangseng.chr3 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Nakanai-Mangseng.chr4.vcf.gz -r ../rfmix4/bisnp.chr4.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr4.txt -m ../rfmix4/Ref.map --chromosome=4 -o Nakanai-Mangseng.chr4 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Nakanai-Mangseng.chr5.vcf.gz -r ../rfmix4/bisnp.chr5.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr5.txt -m ../rfmix4/Ref.map --chromosome=5 -o Nakanai-Mangseng.chr5 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Nakanai-Mangseng.chr6.vcf.gz -r ../rfmix4/bisnp.chr6.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr6.txt -m ../rfmix4/Ref.map --chromosome=6 -o Nakanai-Mangseng.chr6 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Nakanai-Mangseng.chr7.vcf.gz -r ../rfmix4/bisnp.chr7.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr7.txt -m ../rfmix4/Ref.map --chromosome=7 -o Nakanai-Mangseng.chr7 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Nakanai-Mangseng.chr8.vcf.gz -r ../rfmix4/bisnp.chr8.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr8.txt -m ../rfmix4/Ref.map --chromosome=8 -o Nakanai-Mangseng.chr8 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Nakanai-Mangseng.chr9.vcf.gz -r ../rfmix4/bisnp.chr9.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr9.txt -m ../rfmix4/Ref.map --chromosome=9 -o Nakanai-Mangseng.chr9 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Nakanai-Mangseng.chr10.vcf.gz -r ../rfmix4/bisnp.chr10.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr10.txt -m ../rfmix4/Ref.map --chromosome=10 -o Nakanai-Mangseng.chr10 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Nakanai-Mangseng.chr11.vcf.gz -r ../rfmix4/bisnp.chr11.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr11.txt -m ../rfmix4/Ref.map --chromosome=11 -o Nakanai-Mangseng.chr11 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Nakanai-Mangseng.chr12.vcf.gz -r ../rfmix4/bisnp.chr12.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr12.txt -m ../rfmix4/Ref.map --chromosome=12 -o Nakanai-Mangseng.chr12 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Nakanai-Mangseng.chr13.vcf.gz -r ../rfmix4/bisnp.chr13.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr13.txt -m ../rfmix4/Ref.map --chromosome=13 -o Nakanai-Mangseng.chr13 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Nakanai-Mangseng.chr14.vcf.gz -r ../rfmix4/bisnp.chr14.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr14.txt -m ../rfmix4/Ref.map --chromosome=14 -o Nakanai-Mangseng.chr14 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Nakanai-Mangseng.chr15.vcf.gz -r ../rfmix4/bisnp.chr15.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr15.txt -m ../rfmix4/Ref.map --chromosome=15 -o Nakanai-Mangseng.chr15 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Nakanai-Mangseng.chr16.vcf.gz -r ../rfmix4/bisnp.chr16.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr16.txt -m ../rfmix4/Ref.map --chromosome=16 -o Nakanai-Mangseng.chr16 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Nakanai-Mangseng.chr17.vcf.gz -r ../rfmix4/bisnp.chr17.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr17.txt -m ../rfmix4/Ref.map --chromosome=17 -o Nakanai-Mangseng.chr17 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Nakanai-Mangseng.chr18.vcf.gz -r ../rfmix4/bisnp.chr18.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr18.txt -m ../rfmix4/Ref.map --chromosome=18 -o Nakanai-Mangseng.chr18 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Nakanai-Mangseng.chr19.vcf.gz -r ../rfmix4/bisnp.chr19.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr19.txt -m ../rfmix4/Ref.map --chromosome=19 -o Nakanai-Mangseng.chr19 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Nakanai-Mangseng.chr20.vcf.gz -r ../rfmix4/bisnp.chr20.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr20.txt -m ../rfmix4/Ref.map --chromosome=20 -o Nakanai-Mangseng.chr20 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Nakanai-Mangseng.chr21.vcf.gz -r ../rfmix4/bisnp.chr21.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr21.txt -m ../rfmix4/Ref.map --chromosome=21 -o Nakanai-Mangseng.chr21 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Nakanai-Mangseng.chr22.vcf.gz -r ../rfmix4/bisnp.chr22.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr22.txt -m ../rfmix4/Ref.map --chromosome=22 -o Nakanai-Mangseng.chr22 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Bellona-Rennell.chr1.vcf.gz -r ../rfmix4/bisnp.chr1.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr1.txt -m ../rfmix4/Ref.map --chromosome=1 -o Bellona-Rennell.chr1 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Bellona-Rennell.chr2.vcf.gz -r ../rfmix4/bisnp.chr2.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr2.txt -m ../rfmix4/Ref.map --chromosome=2 -o Bellona-Rennell.chr2 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Bellona-Rennell.chr3.vcf.gz -r ../rfmix4/bisnp.chr3.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr3.txt -m ../rfmix4/Ref.map --chromosome=3 -o Bellona-Rennell.chr3 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Bellona-Rennell.chr4.vcf.gz -r ../rfmix4/bisnp.chr4.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr4.txt -m ../rfmix4/Ref.map --chromosome=4 -o Bellona-Rennell.chr4 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Bellona-Rennell.chr5.vcf.gz -r ../rfmix4/bisnp.chr5.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr5.txt -m ../rfmix4/Ref.map --chromosome=5 -o Bellona-Rennell.chr5 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Bellona-Rennell.chr6.vcf.gz -r ../rfmix4/bisnp.chr6.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr6.txt -m ../rfmix4/Ref.map --chromosome=6 -o Bellona-Rennell.chr6 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Bellona-Rennell.chr7.vcf.gz -r ../rfmix4/bisnp.chr7.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr7.txt -m ../rfmix4/Ref.map --chromosome=7 -o Bellona-Rennell.chr7 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Bellona-Rennell.chr8.vcf.gz -r ../rfmix4/bisnp.chr8.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr8.txt -m ../rfmix4/Ref.map --chromosome=8 -o Bellona-Rennell.chr8 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Bellona-Rennell.chr9.vcf.gz -r ../rfmix4/bisnp.chr9.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr9.txt -m ../rfmix4/Ref.map --chromosome=9 -o Bellona-Rennell.chr9 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Bellona-Rennell.chr10.vcf.gz -r ../rfmix4/bisnp.chr10.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr10.txt -m ../rfmix4/Ref.map --chromosome=10 -o Bellona-Rennell.chr10 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Bellona-Rennell.chr11.vcf.gz -r ../rfmix4/bisnp.chr11.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr11.txt -m ../rfmix4/Ref.map --chromosome=11 -o Bellona-Rennell.chr11 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Bellona-Rennell.chr12.vcf.gz -r ../rfmix4/bisnp.chr12.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr12.txt -m ../rfmix4/Ref.map --chromosome=12 -o Bellona-Rennell.chr12 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Bellona-Rennell.chr13.vcf.gz -r ../rfmix4/bisnp.chr13.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr13.txt -m ../rfmix4/Ref.map --chromosome=13 -o Bellona-Rennell.chr13 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Bellona-Rennell.chr14.vcf.gz -r ../rfmix4/bisnp.chr14.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr14.txt -m ../rfmix4/Ref.map --chromosome=14 -o Bellona-Rennell.chr14 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Bellona-Rennell.chr15.vcf.gz -r ../rfmix4/bisnp.chr15.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr15.txt -m ../rfmix4/Ref.map --chromosome=15 -o Bellona-Rennell.chr15 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Bellona-Rennell.chr16.vcf.gz -r ../rfmix4/bisnp.chr16.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr16.txt -m ../rfmix4/Ref.map --chromosome=16 -o Bellona-Rennell.chr16 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Bellona-Rennell.chr17.vcf.gz -r ../rfmix4/bisnp.chr17.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr17.txt -m ../rfmix4/Ref.map --chromosome=17 -o Bellona-Rennell.chr17 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Bellona-Rennell.chr18.vcf.gz -r ../rfmix4/bisnp.chr18.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr18.txt -m ../rfmix4/Ref.map --chromosome=18 -o Bellona-Rennell.chr18 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Bellona-Rennell.chr19.vcf.gz -r ../rfmix4/bisnp.chr19.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr19.txt -m ../rfmix4/Ref.map --chromosome=19 -o Bellona-Rennell.chr19 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Bellona-Rennell.chr20.vcf.gz -r ../rfmix4/bisnp.chr20.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr20.txt -m ../rfmix4/Ref.map --chromosome=20 -o Bellona-Rennell.chr20 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Bellona-Rennell.chr21.vcf.gz -r ../rfmix4/bisnp.chr21.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr21.txt -m ../rfmix4/Ref.map --chromosome=21 -o Bellona-Rennell.chr21 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Bellona-Rennell.chr22.vcf.gz -r ../rfmix4/bisnp.chr22.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr22.txt -m ../rfmix4/Ref.map --chromosome=22 -o Bellona-Rennell.chr22 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Atayal.chr1.vcf.gz -r ../rfmix4/bisnp.chr1.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr1.txt -m ../rfmix4/Ref.map --chromosome=1 -o Atayal.chr1 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Atayal.chr2.vcf.gz -r ../rfmix4/bisnp.chr2.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr2.txt -m ../rfmix4/Ref.map --chromosome=2 -o Atayal.chr2 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Atayal.chr3.vcf.gz -r ../rfmix4/bisnp.chr3.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr3.txt -m ../rfmix4/Ref.map --chromosome=3 -o Atayal.chr3 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Atayal.chr4.vcf.gz -r ../rfmix4/bisnp.chr4.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr4.txt -m ../rfmix4/Ref.map --chromosome=4 -o Atayal.chr4 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Atayal.chr5.vcf.gz -r ../rfmix4/bisnp.chr5.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr5.txt -m ../rfmix4/Ref.map --chromosome=5 -o Atayal.chr5 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Atayal.chr6.vcf.gz -r ../rfmix4/bisnp.chr6.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr6.txt -m ../rfmix4/Ref.map --chromosome=6 -o Atayal.chr6 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Atayal.chr7.vcf.gz -r ../rfmix4/bisnp.chr7.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr7.txt -m ../rfmix4/Ref.map --chromosome=7 -o Atayal.chr7 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Atayal.chr8.vcf.gz -r ../rfmix4/bisnp.chr8.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr8.txt -m ../rfmix4/Ref.map --chromosome=8 -o Atayal.chr8 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Atayal.chr9.vcf.gz -r ../rfmix4/bisnp.chr9.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr9.txt -m ../rfmix4/Ref.map --chromosome=9 -o Atayal.chr9 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Atayal.chr10.vcf.gz -r ../rfmix4/bisnp.chr10.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr10.txt -m ../rfmix4/Ref.map --chromosome=10 -o Atayal.chr10 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Atayal.chr11.vcf.gz -r ../rfmix4/bisnp.chr11.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr11.txt -m ../rfmix4/Ref.map --chromosome=11 -o Atayal.chr11 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Atayal.chr12.vcf.gz -r ../rfmix4/bisnp.chr12.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr12.txt -m ../rfmix4/Ref.map --chromosome=12 -o Atayal.chr12 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Atayal.chr13.vcf.gz -r ../rfmix4/bisnp.chr13.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr13.txt -m ../rfmix4/Ref.map --chromosome=13 -o Atayal.chr13 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Atayal.chr14.vcf.gz -r ../rfmix4/bisnp.chr14.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr14.txt -m ../rfmix4/Ref.map --chromosome=14 -o Atayal.chr14 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Atayal.chr15.vcf.gz -r ../rfmix4/bisnp.chr15.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr15.txt -m ../rfmix4/Ref.map --chromosome=15 -o Atayal.chr15 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Atayal.chr16.vcf.gz -r ../rfmix4/bisnp.chr16.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr16.txt -m ../rfmix4/Ref.map --chromosome=16 -o Atayal.chr16 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Atayal.chr17.vcf.gz -r ../rfmix4/bisnp.chr17.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr17.txt -m ../rfmix4/Ref.map --chromosome=17 -o Atayal.chr17 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Atayal.chr18.vcf.gz -r ../rfmix4/bisnp.chr18.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr18.txt -m ../rfmix4/Ref.map --chromosome=18 -o Atayal.chr18 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Atayal.chr19.vcf.gz -r ../rfmix4/bisnp.chr19.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr19.txt -m ../rfmix4/Ref.map --chromosome=19 -o Atayal.chr19 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Atayal.chr20.vcf.gz -r ../rfmix4/bisnp.chr20.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr20.txt -m ../rfmix4/Ref.map --chromosome=20 -o Atayal.chr20 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Atayal.chr21.vcf.gz -r ../rfmix4/bisnp.chr21.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr21.txt -m ../rfmix4/Ref.map --chromosome=21 -o Atayal.chr21 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Atayal.chr22.vcf.gz -r ../rfmix4/bisnp.chr22.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr22.txt -m ../rfmix4/Ref.map --chromosome=22 -o Atayal.chr22 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Paiwan.chr1.vcf.gz -r ../rfmix4/bisnp.chr1.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr1.txt -m ../rfmix4/Ref.map --chromosome=1 -o Paiwan.chr1 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Paiwan.chr2.vcf.gz -r ../rfmix4/bisnp.chr2.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr2.txt -m ../rfmix4/Ref.map --chromosome=2 -o Paiwan.chr2 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Paiwan.chr3.vcf.gz -r ../rfmix4/bisnp.chr3.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr3.txt -m ../rfmix4/Ref.map --chromosome=3 -o Paiwan.chr3 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Paiwan.chr4.vcf.gz -r ../rfmix4/bisnp.chr4.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr4.txt -m ../rfmix4/Ref.map --chromosome=4 -o Paiwan.chr4 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Paiwan.chr5.vcf.gz -r ../rfmix4/bisnp.chr5.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr5.txt -m ../rfmix4/Ref.map --chromosome=5 -o Paiwan.chr5 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Paiwan.chr6.vcf.gz -r ../rfmix4/bisnp.chr6.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr6.txt -m ../rfmix4/Ref.map --chromosome=6 -o Paiwan.chr6 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Paiwan.chr7.vcf.gz -r ../rfmix4/bisnp.chr7.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr7.txt -m ../rfmix4/Ref.map --chromosome=7 -o Paiwan.chr7 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Paiwan.chr8.vcf.gz -r ../rfmix4/bisnp.chr8.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr8.txt -m ../rfmix4/Ref.map --chromosome=8 -o Paiwan.chr8 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Paiwan.chr9.vcf.gz -r ../rfmix4/bisnp.chr9.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr9.txt -m ../rfmix4/Ref.map --chromosome=9 -o Paiwan.chr9 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Paiwan.chr10.vcf.gz -r ../rfmix4/bisnp.chr10.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr10.txt -m ../rfmix4/Ref.map --chromosome=10 -o Paiwan.chr10 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Paiwan.chr11.vcf.gz -r ../rfmix4/bisnp.chr11.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr11.txt -m ../rfmix4/Ref.map --chromosome=11 -o Paiwan.chr11 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Paiwan.chr12.vcf.gz -r ../rfmix4/bisnp.chr12.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr12.txt -m ../rfmix4/Ref.map --chromosome=12 -o Paiwan.chr12 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Paiwan.chr13.vcf.gz -r ../rfmix4/bisnp.chr13.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr13.txt -m ../rfmix4/Ref.map --chromosome=13 -o Paiwan.chr13 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Paiwan.chr14.vcf.gz -r ../rfmix4/bisnp.chr14.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr14.txt -m ../rfmix4/Ref.map --chromosome=14 -o Paiwan.chr14 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Paiwan.chr15.vcf.gz -r ../rfmix4/bisnp.chr15.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr15.txt -m ../rfmix4/Ref.map --chromosome=15 -o Paiwan.chr15 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Paiwan.chr16.vcf.gz -r ../rfmix4/bisnp.chr16.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr16.txt -m ../rfmix4/Ref.map --chromosome=16 -o Paiwan.chr16 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Paiwan.chr17.vcf.gz -r ../rfmix4/bisnp.chr17.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr17.txt -m ../rfmix4/Ref.map --chromosome=17 -o Paiwan.chr17 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Paiwan.chr18.vcf.gz -r ../rfmix4/bisnp.chr18.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr18.txt -m ../rfmix4/Ref.map --chromosome=18 -o Paiwan.chr18 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Paiwan.chr19.vcf.gz -r ../rfmix4/bisnp.chr19.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr19.txt -m ../rfmix4/Ref.map --chromosome=19 -o Paiwan.chr19 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Paiwan.chr20.vcf.gz -r ../rfmix4/bisnp.chr20.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr20.txt -m ../rfmix4/Ref.map --chromosome=20 -o Paiwan.chr20 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Paiwan.chr21.vcf.gz -r ../rfmix4/bisnp.chr21.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr21.txt -m ../rfmix4/Ref.map --chromosome=21 -o Paiwan.chr21 -s 0.03 --n-threads=16
rfmix -f ../rfmix4/Paiwan.chr22.vcf.gz -r ../rfmix4/bisnp.chr22.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr22.txt -m ../rfmix4/Ref.map --chromosome=22 -o Paiwan.chr22 -s 0.03 --n-threads=16
