rfmix -f ../rfmix4/Ata.chr1.vcf.gz -r ../rfmix4/bisnp.chr1.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr1.txt -m ../rfmix4/Ref.map --chromosome=1 -o Ata.chr1 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Ata.chr2.vcf.gz -r ../rfmix4/bisnp.chr2.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr2.txt -m ../rfmix4/Ref.map --chromosome=2 -o Ata.chr2 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Ata.chr3.vcf.gz -r ../rfmix4/bisnp.chr3.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr3.txt -m ../rfmix4/Ref.map --chromosome=3 -o Ata.chr3 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Ata.chr4.vcf.gz -r ../rfmix4/bisnp.chr4.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr4.txt -m ../rfmix4/Ref.map --chromosome=4 -o Ata.chr4 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Ata.chr5.vcf.gz -r ../rfmix4/bisnp.chr5.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr5.txt -m ../rfmix4/Ref.map --chromosome=5 -o Ata.chr5 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Ata.chr6.vcf.gz -r ../rfmix4/bisnp.chr6.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr6.txt -m ../rfmix4/Ref.map --chromosome=6 -o Ata.chr6 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Ata.chr7.vcf.gz -r ../rfmix4/bisnp.chr7.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr7.txt -m ../rfmix4/Ref.map --chromosome=7 -o Ata.chr7 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Ata.chr8.vcf.gz -r ../rfmix4/bisnp.chr8.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr8.txt -m ../rfmix4/Ref.map --chromosome=8 -o Ata.chr8 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Ata.chr9.vcf.gz -r ../rfmix4/bisnp.chr9.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr9.txt -m ../rfmix4/Ref.map --chromosome=9 -o Ata.chr9 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Ata.chr10.vcf.gz -r ../rfmix4/bisnp.chr10.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr10.txt -m ../rfmix4/Ref.map --chromosome=10 -o Ata.chr10 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Ata.chr11.vcf.gz -r ../rfmix4/bisnp.chr11.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr11.txt -m ../rfmix4/Ref.map --chromosome=11 -o Ata.chr11 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Ata.chr12.vcf.gz -r ../rfmix4/bisnp.chr12.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr12.txt -m ../rfmix4/Ref.map --chromosome=12 -o Ata.chr12 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Ata.chr13.vcf.gz -r ../rfmix4/bisnp.chr13.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr13.txt -m ../rfmix4/Ref.map --chromosome=13 -o Ata.chr13 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Ata.chr14.vcf.gz -r ../rfmix4/bisnp.chr14.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr14.txt -m ../rfmix4/Ref.map --chromosome=14 -o Ata.chr14 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Ata.chr15.vcf.gz -r ../rfmix4/bisnp.chr15.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr15.txt -m ../rfmix4/Ref.map --chromosome=15 -o Ata.chr15 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Ata.chr16.vcf.gz -r ../rfmix4/bisnp.chr16.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr16.txt -m ../rfmix4/Ref.map --chromosome=16 -o Ata.chr16 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Ata.chr17.vcf.gz -r ../rfmix4/bisnp.chr17.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr17.txt -m ../rfmix4/Ref.map --chromosome=17 -o Ata.chr17 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Ata.chr18.vcf.gz -r ../rfmix4/bisnp.chr18.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr18.txt -m ../rfmix4/Ref.map --chromosome=18 -o Ata.chr18 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Ata.chr19.vcf.gz -r ../rfmix4/bisnp.chr19.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr19.txt -m ../rfmix4/Ref.map --chromosome=19 -o Ata.chr19 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Ata.chr20.vcf.gz -r ../rfmix4/bisnp.chr20.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr20.txt -m ../rfmix4/Ref.map --chromosome=20 -o Ata.chr20 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Ata.chr21.vcf.gz -r ../rfmix4/bisnp.chr21.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr21.txt -m ../rfmix4/Ref.map --chromosome=21 -o Ata.chr21 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Ata.chr22.vcf.gz -r ../rfmix4/bisnp.chr22.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr22.txt -m ../rfmix4/Ref.map --chromosome=22 -o Ata.chr22 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Agta.chr1.vcf.gz -r ../rfmix4/bisnp.chr1.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr1.txt -m ../rfmix4/Ref.map --chromosome=1 -o Agta.chr1 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Agta.chr2.vcf.gz -r ../rfmix4/bisnp.chr2.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr2.txt -m ../rfmix4/Ref.map --chromosome=2 -o Agta.chr2 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Agta.chr3.vcf.gz -r ../rfmix4/bisnp.chr3.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr3.txt -m ../rfmix4/Ref.map --chromosome=3 -o Agta.chr3 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Agta.chr4.vcf.gz -r ../rfmix4/bisnp.chr4.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr4.txt -m ../rfmix4/Ref.map --chromosome=4 -o Agta.chr4 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Agta.chr5.vcf.gz -r ../rfmix4/bisnp.chr5.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr5.txt -m ../rfmix4/Ref.map --chromosome=5 -o Agta.chr5 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Agta.chr6.vcf.gz -r ../rfmix4/bisnp.chr6.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr6.txt -m ../rfmix4/Ref.map --chromosome=6 -o Agta.chr6 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Agta.chr7.vcf.gz -r ../rfmix4/bisnp.chr7.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr7.txt -m ../rfmix4/Ref.map --chromosome=7 -o Agta.chr7 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Agta.chr8.vcf.gz -r ../rfmix4/bisnp.chr8.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr8.txt -m ../rfmix4/Ref.map --chromosome=8 -o Agta.chr8 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Agta.chr9.vcf.gz -r ../rfmix4/bisnp.chr9.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr9.txt -m ../rfmix4/Ref.map --chromosome=9 -o Agta.chr9 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Agta.chr10.vcf.gz -r ../rfmix4/bisnp.chr10.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr10.txt -m ../rfmix4/Ref.map --chromosome=10 -o Agta.chr10 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Agta.chr11.vcf.gz -r ../rfmix4/bisnp.chr11.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr11.txt -m ../rfmix4/Ref.map --chromosome=11 -o Agta.chr11 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Agta.chr12.vcf.gz -r ../rfmix4/bisnp.chr12.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr12.txt -m ../rfmix4/Ref.map --chromosome=12 -o Agta.chr12 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Agta.chr13.vcf.gz -r ../rfmix4/bisnp.chr13.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr13.txt -m ../rfmix4/Ref.map --chromosome=13 -o Agta.chr13 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Agta.chr14.vcf.gz -r ../rfmix4/bisnp.chr14.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr14.txt -m ../rfmix4/Ref.map --chromosome=14 -o Agta.chr14 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Agta.chr15.vcf.gz -r ../rfmix4/bisnp.chr15.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr15.txt -m ../rfmix4/Ref.map --chromosome=15 -o Agta.chr15 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Agta.chr16.vcf.gz -r ../rfmix4/bisnp.chr16.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr16.txt -m ../rfmix4/Ref.map --chromosome=16 -o Agta.chr16 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Agta.chr17.vcf.gz -r ../rfmix4/bisnp.chr17.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr17.txt -m ../rfmix4/Ref.map --chromosome=17 -o Agta.chr17 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Agta.chr18.vcf.gz -r ../rfmix4/bisnp.chr18.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr18.txt -m ../rfmix4/Ref.map --chromosome=18 -o Agta.chr18 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Agta.chr19.vcf.gz -r ../rfmix4/bisnp.chr19.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr19.txt -m ../rfmix4/Ref.map --chromosome=19 -o Agta.chr19 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Agta.chr20.vcf.gz -r ../rfmix4/bisnp.chr20.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr20.txt -m ../rfmix4/Ref.map --chromosome=20 -o Agta.chr20 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Agta.chr21.vcf.gz -r ../rfmix4/bisnp.chr21.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr21.txt -m ../rfmix4/Ref.map --chromosome=21 -o Agta.chr21 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Agta.chr22.vcf.gz -r ../rfmix4/bisnp.chr22.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr22.txt -m ../rfmix4/Ref.map --chromosome=22 -o Agta.chr22 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Baining-Kagat.chr1.vcf.gz -r ../rfmix4/bisnp.chr1.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr1.txt -m ../rfmix4/Ref.map --chromosome=1 -o Baining-Kagat.chr1 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Baining-Kagat.chr2.vcf.gz -r ../rfmix4/bisnp.chr2.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr2.txt -m ../rfmix4/Ref.map --chromosome=2 -o Baining-Kagat.chr2 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Baining-Kagat.chr3.vcf.gz -r ../rfmix4/bisnp.chr3.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr3.txt -m ../rfmix4/Ref.map --chromosome=3 -o Baining-Kagat.chr3 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Baining-Kagat.chr4.vcf.gz -r ../rfmix4/bisnp.chr4.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr4.txt -m ../rfmix4/Ref.map --chromosome=4 -o Baining-Kagat.chr4 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Baining-Kagat.chr5.vcf.gz -r ../rfmix4/bisnp.chr5.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr5.txt -m ../rfmix4/Ref.map --chromosome=5 -o Baining-Kagat.chr5 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Baining-Kagat.chr6.vcf.gz -r ../rfmix4/bisnp.chr6.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr6.txt -m ../rfmix4/Ref.map --chromosome=6 -o Baining-Kagat.chr6 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Baining-Kagat.chr7.vcf.gz -r ../rfmix4/bisnp.chr7.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr7.txt -m ../rfmix4/Ref.map --chromosome=7 -o Baining-Kagat.chr7 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Baining-Kagat.chr8.vcf.gz -r ../rfmix4/bisnp.chr8.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr8.txt -m ../rfmix4/Ref.map --chromosome=8 -o Baining-Kagat.chr8 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Baining-Kagat.chr9.vcf.gz -r ../rfmix4/bisnp.chr9.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr9.txt -m ../rfmix4/Ref.map --chromosome=9 -o Baining-Kagat.chr9 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Baining-Kagat.chr10.vcf.gz -r ../rfmix4/bisnp.chr10.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr10.txt -m ../rfmix4/Ref.map --chromosome=10 -o Baining-Kagat.chr10 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Baining-Kagat.chr11.vcf.gz -r ../rfmix4/bisnp.chr11.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr11.txt -m ../rfmix4/Ref.map --chromosome=11 -o Baining-Kagat.chr11 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Baining-Kagat.chr12.vcf.gz -r ../rfmix4/bisnp.chr12.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr12.txt -m ../rfmix4/Ref.map --chromosome=12 -o Baining-Kagat.chr12 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Baining-Kagat.chr13.vcf.gz -r ../rfmix4/bisnp.chr13.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr13.txt -m ../rfmix4/Ref.map --chromosome=13 -o Baining-Kagat.chr13 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Baining-Kagat.chr14.vcf.gz -r ../rfmix4/bisnp.chr14.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr14.txt -m ../rfmix4/Ref.map --chromosome=14 -o Baining-Kagat.chr14 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Baining-Kagat.chr15.vcf.gz -r ../rfmix4/bisnp.chr15.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr15.txt -m ../rfmix4/Ref.map --chromosome=15 -o Baining-Kagat.chr15 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Baining-Kagat.chr16.vcf.gz -r ../rfmix4/bisnp.chr16.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr16.txt -m ../rfmix4/Ref.map --chromosome=16 -o Baining-Kagat.chr16 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Baining-Kagat.chr17.vcf.gz -r ../rfmix4/bisnp.chr17.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr17.txt -m ../rfmix4/Ref.map --chromosome=17 -o Baining-Kagat.chr17 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Baining-Kagat.chr18.vcf.gz -r ../rfmix4/bisnp.chr18.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr18.txt -m ../rfmix4/Ref.map --chromosome=18 -o Baining-Kagat.chr18 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Baining-Kagat.chr19.vcf.gz -r ../rfmix4/bisnp.chr19.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr19.txt -m ../rfmix4/Ref.map --chromosome=19 -o Baining-Kagat.chr19 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Baining-Kagat.chr20.vcf.gz -r ../rfmix4/bisnp.chr20.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr20.txt -m ../rfmix4/Ref.map --chromosome=20 -o Baining-Kagat.chr20 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Baining-Kagat.chr21.vcf.gz -r ../rfmix4/bisnp.chr21.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr21.txt -m ../rfmix4/Ref.map --chromosome=21 -o Baining-Kagat.chr21 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Baining-Kagat.chr22.vcf.gz -r ../rfmix4/bisnp.chr22.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr22.txt -m ../rfmix4/Ref.map --chromosome=22 -o Baining-Kagat.chr22 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Baining-Mali.chr1.vcf.gz -r ../rfmix4/bisnp.chr1.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr1.txt -m ../rfmix4/Ref.map --chromosome=1 -o Baining-Mali.chr1 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Baining-Mali.chr2.vcf.gz -r ../rfmix4/bisnp.chr2.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr2.txt -m ../rfmix4/Ref.map --chromosome=2 -o Baining-Mali.chr2 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Baining-Mali.chr3.vcf.gz -r ../rfmix4/bisnp.chr3.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr3.txt -m ../rfmix4/Ref.map --chromosome=3 -o Baining-Mali.chr3 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Baining-Mali.chr4.vcf.gz -r ../rfmix4/bisnp.chr4.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr4.txt -m ../rfmix4/Ref.map --chromosome=4 -o Baining-Mali.chr4 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Baining-Mali.chr5.vcf.gz -r ../rfmix4/bisnp.chr5.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr5.txt -m ../rfmix4/Ref.map --chromosome=5 -o Baining-Mali.chr5 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Baining-Mali.chr6.vcf.gz -r ../rfmix4/bisnp.chr6.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr6.txt -m ../rfmix4/Ref.map --chromosome=6 -o Baining-Mali.chr6 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Baining-Mali.chr7.vcf.gz -r ../rfmix4/bisnp.chr7.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr7.txt -m ../rfmix4/Ref.map --chromosome=7 -o Baining-Mali.chr7 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Baining-Mali.chr8.vcf.gz -r ../rfmix4/bisnp.chr8.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr8.txt -m ../rfmix4/Ref.map --chromosome=8 -o Baining-Mali.chr8 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Baining-Mali.chr9.vcf.gz -r ../rfmix4/bisnp.chr9.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr9.txt -m ../rfmix4/Ref.map --chromosome=9 -o Baining-Mali.chr9 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Baining-Mali.chr10.vcf.gz -r ../rfmix4/bisnp.chr10.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr10.txt -m ../rfmix4/Ref.map --chromosome=10 -o Baining-Mali.chr10 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Baining-Mali.chr11.vcf.gz -r ../rfmix4/bisnp.chr11.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr11.txt -m ../rfmix4/Ref.map --chromosome=11 -o Baining-Mali.chr11 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Baining-Mali.chr12.vcf.gz -r ../rfmix4/bisnp.chr12.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr12.txt -m ../rfmix4/Ref.map --chromosome=12 -o Baining-Mali.chr12 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Baining-Mali.chr13.vcf.gz -r ../rfmix4/bisnp.chr13.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr13.txt -m ../rfmix4/Ref.map --chromosome=13 -o Baining-Mali.chr13 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Baining-Mali.chr14.vcf.gz -r ../rfmix4/bisnp.chr14.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr14.txt -m ../rfmix4/Ref.map --chromosome=14 -o Baining-Mali.chr14 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Baining-Mali.chr15.vcf.gz -r ../rfmix4/bisnp.chr15.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr15.txt -m ../rfmix4/Ref.map --chromosome=15 -o Baining-Mali.chr15 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Baining-Mali.chr16.vcf.gz -r ../rfmix4/bisnp.chr16.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr16.txt -m ../rfmix4/Ref.map --chromosome=16 -o Baining-Mali.chr16 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Baining-Mali.chr17.vcf.gz -r ../rfmix4/bisnp.chr17.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr17.txt -m ../rfmix4/Ref.map --chromosome=17 -o Baining-Mali.chr17 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Baining-Mali.chr18.vcf.gz -r ../rfmix4/bisnp.chr18.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr18.txt -m ../rfmix4/Ref.map --chromosome=18 -o Baining-Mali.chr18 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Baining-Mali.chr19.vcf.gz -r ../rfmix4/bisnp.chr19.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr19.txt -m ../rfmix4/Ref.map --chromosome=19 -o Baining-Mali.chr19 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Baining-Mali.chr20.vcf.gz -r ../rfmix4/bisnp.chr20.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr20.txt -m ../rfmix4/Ref.map --chromosome=20 -o Baining-Mali.chr20 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Baining-Mali.chr21.vcf.gz -r ../rfmix4/bisnp.chr21.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr21.txt -m ../rfmix4/Ref.map --chromosome=21 -o Baining-Mali.chr21 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Baining-Mali.chr22.vcf.gz -r ../rfmix4/bisnp.chr22.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr22.txt -m ../rfmix4/Ref.map --chromosome=22 -o Baining-Mali.chr22 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Bellona.chr1.vcf.gz -r ../rfmix4/bisnp.chr1.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr1.txt -m ../rfmix4/Ref.map --chromosome=1 -o Bellona.chr1 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Bellona.chr2.vcf.gz -r ../rfmix4/bisnp.chr2.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr2.txt -m ../rfmix4/Ref.map --chromosome=2 -o Bellona.chr2 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Bellona.chr3.vcf.gz -r ../rfmix4/bisnp.chr3.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr3.txt -m ../rfmix4/Ref.map --chromosome=3 -o Bellona.chr3 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Bellona.chr4.vcf.gz -r ../rfmix4/bisnp.chr4.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr4.txt -m ../rfmix4/Ref.map --chromosome=4 -o Bellona.chr4 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Bellona.chr5.vcf.gz -r ../rfmix4/bisnp.chr5.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr5.txt -m ../rfmix4/Ref.map --chromosome=5 -o Bellona.chr5 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Bellona.chr6.vcf.gz -r ../rfmix4/bisnp.chr6.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr6.txt -m ../rfmix4/Ref.map --chromosome=6 -o Bellona.chr6 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Bellona.chr7.vcf.gz -r ../rfmix4/bisnp.chr7.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr7.txt -m ../rfmix4/Ref.map --chromosome=7 -o Bellona.chr7 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Bellona.chr8.vcf.gz -r ../rfmix4/bisnp.chr8.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr8.txt -m ../rfmix4/Ref.map --chromosome=8 -o Bellona.chr8 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Bellona.chr9.vcf.gz -r ../rfmix4/bisnp.chr9.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr9.txt -m ../rfmix4/Ref.map --chromosome=9 -o Bellona.chr9 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Bellona.chr10.vcf.gz -r ../rfmix4/bisnp.chr10.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr10.txt -m ../rfmix4/Ref.map --chromosome=10 -o Bellona.chr10 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Bellona.chr11.vcf.gz -r ../rfmix4/bisnp.chr11.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr11.txt -m ../rfmix4/Ref.map --chromosome=11 -o Bellona.chr11 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Bellona.chr12.vcf.gz -r ../rfmix4/bisnp.chr12.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr12.txt -m ../rfmix4/Ref.map --chromosome=12 -o Bellona.chr12 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Bellona.chr13.vcf.gz -r ../rfmix4/bisnp.chr13.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr13.txt -m ../rfmix4/Ref.map --chromosome=13 -o Bellona.chr13 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Bellona.chr14.vcf.gz -r ../rfmix4/bisnp.chr14.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr14.txt -m ../rfmix4/Ref.map --chromosome=14 -o Bellona.chr14 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Bellona.chr15.vcf.gz -r ../rfmix4/bisnp.chr15.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr15.txt -m ../rfmix4/Ref.map --chromosome=15 -o Bellona.chr15 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Bellona.chr16.vcf.gz -r ../rfmix4/bisnp.chr16.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr16.txt -m ../rfmix4/Ref.map --chromosome=16 -o Bellona.chr16 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Bellona.chr17.vcf.gz -r ../rfmix4/bisnp.chr17.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr17.txt -m ../rfmix4/Ref.map --chromosome=17 -o Bellona.chr17 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Bellona.chr18.vcf.gz -r ../rfmix4/bisnp.chr18.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr18.txt -m ../rfmix4/Ref.map --chromosome=18 -o Bellona.chr18 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Bellona.chr19.vcf.gz -r ../rfmix4/bisnp.chr19.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr19.txt -m ../rfmix4/Ref.map --chromosome=19 -o Bellona.chr19 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Bellona.chr20.vcf.gz -r ../rfmix4/bisnp.chr20.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr20.txt -m ../rfmix4/Ref.map --chromosome=20 -o Bellona.chr20 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Bellona.chr21.vcf.gz -r ../rfmix4/bisnp.chr21.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr21.txt -m ../rfmix4/Ref.map --chromosome=21 -o Bellona.chr21 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Bellona.chr22.vcf.gz -r ../rfmix4/bisnp.chr22.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr22.txt -m ../rfmix4/Ref.map --chromosome=22 -o Bellona.chr22 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Cebuano.chr1.vcf.gz -r ../rfmix4/bisnp.chr1.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr1.txt -m ../rfmix4/Ref.map --chromosome=1 -o Cebuano.chr1 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Cebuano.chr2.vcf.gz -r ../rfmix4/bisnp.chr2.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr2.txt -m ../rfmix4/Ref.map --chromosome=2 -o Cebuano.chr2 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Cebuano.chr3.vcf.gz -r ../rfmix4/bisnp.chr3.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr3.txt -m ../rfmix4/Ref.map --chromosome=3 -o Cebuano.chr3 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Cebuano.chr4.vcf.gz -r ../rfmix4/bisnp.chr4.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr4.txt -m ../rfmix4/Ref.map --chromosome=4 -o Cebuano.chr4 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Cebuano.chr5.vcf.gz -r ../rfmix4/bisnp.chr5.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr5.txt -m ../rfmix4/Ref.map --chromosome=5 -o Cebuano.chr5 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Cebuano.chr6.vcf.gz -r ../rfmix4/bisnp.chr6.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr6.txt -m ../rfmix4/Ref.map --chromosome=6 -o Cebuano.chr6 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Cebuano.chr7.vcf.gz -r ../rfmix4/bisnp.chr7.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr7.txt -m ../rfmix4/Ref.map --chromosome=7 -o Cebuano.chr7 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Cebuano.chr8.vcf.gz -r ../rfmix4/bisnp.chr8.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr8.txt -m ../rfmix4/Ref.map --chromosome=8 -o Cebuano.chr8 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Cebuano.chr9.vcf.gz -r ../rfmix4/bisnp.chr9.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr9.txt -m ../rfmix4/Ref.map --chromosome=9 -o Cebuano.chr9 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Cebuano.chr10.vcf.gz -r ../rfmix4/bisnp.chr10.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr10.txt -m ../rfmix4/Ref.map --chromosome=10 -o Cebuano.chr10 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Cebuano.chr11.vcf.gz -r ../rfmix4/bisnp.chr11.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr11.txt -m ../rfmix4/Ref.map --chromosome=11 -o Cebuano.chr11 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Cebuano.chr12.vcf.gz -r ../rfmix4/bisnp.chr12.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr12.txt -m ../rfmix4/Ref.map --chromosome=12 -o Cebuano.chr12 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Cebuano.chr13.vcf.gz -r ../rfmix4/bisnp.chr13.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr13.txt -m ../rfmix4/Ref.map --chromosome=13 -o Cebuano.chr13 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Cebuano.chr14.vcf.gz -r ../rfmix4/bisnp.chr14.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr14.txt -m ../rfmix4/Ref.map --chromosome=14 -o Cebuano.chr14 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Cebuano.chr15.vcf.gz -r ../rfmix4/bisnp.chr15.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr15.txt -m ../rfmix4/Ref.map --chromosome=15 -o Cebuano.chr15 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Cebuano.chr16.vcf.gz -r ../rfmix4/bisnp.chr16.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr16.txt -m ../rfmix4/Ref.map --chromosome=16 -o Cebuano.chr16 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Cebuano.chr17.vcf.gz -r ../rfmix4/bisnp.chr17.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr17.txt -m ../rfmix4/Ref.map --chromosome=17 -o Cebuano.chr17 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Cebuano.chr18.vcf.gz -r ../rfmix4/bisnp.chr18.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr18.txt -m ../rfmix4/Ref.map --chromosome=18 -o Cebuano.chr18 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Cebuano.chr19.vcf.gz -r ../rfmix4/bisnp.chr19.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr19.txt -m ../rfmix4/Ref.map --chromosome=19 -o Cebuano.chr19 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Cebuano.chr20.vcf.gz -r ../rfmix4/bisnp.chr20.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr20.txt -m ../rfmix4/Ref.map --chromosome=20 -o Cebuano.chr20 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Cebuano.chr21.vcf.gz -r ../rfmix4/bisnp.chr21.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr21.txt -m ../rfmix4/Ref.map --chromosome=21 -o Cebuano.chr21 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Cebuano.chr22.vcf.gz -r ../rfmix4/bisnp.chr22.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr22.txt -m ../rfmix4/Ref.map --chromosome=22 -o Cebuano.chr22 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Goroka.chr1.vcf.gz -r ../rfmix4/bisnp.chr1.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr1.txt -m ../rfmix4/Ref.map --chromosome=1 -o Goroka.chr1 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Goroka.chr2.vcf.gz -r ../rfmix4/bisnp.chr2.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr2.txt -m ../rfmix4/Ref.map --chromosome=2 -o Goroka.chr2 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Goroka.chr3.vcf.gz -r ../rfmix4/bisnp.chr3.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr3.txt -m ../rfmix4/Ref.map --chromosome=3 -o Goroka.chr3 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Goroka.chr4.vcf.gz -r ../rfmix4/bisnp.chr4.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr4.txt -m ../rfmix4/Ref.map --chromosome=4 -o Goroka.chr4 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Goroka.chr5.vcf.gz -r ../rfmix4/bisnp.chr5.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr5.txt -m ../rfmix4/Ref.map --chromosome=5 -o Goroka.chr5 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Goroka.chr6.vcf.gz -r ../rfmix4/bisnp.chr6.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr6.txt -m ../rfmix4/Ref.map --chromosome=6 -o Goroka.chr6 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Goroka.chr7.vcf.gz -r ../rfmix4/bisnp.chr7.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr7.txt -m ../rfmix4/Ref.map --chromosome=7 -o Goroka.chr7 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Goroka.chr8.vcf.gz -r ../rfmix4/bisnp.chr8.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr8.txt -m ../rfmix4/Ref.map --chromosome=8 -o Goroka.chr8 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Goroka.chr9.vcf.gz -r ../rfmix4/bisnp.chr9.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr9.txt -m ../rfmix4/Ref.map --chromosome=9 -o Goroka.chr9 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Goroka.chr10.vcf.gz -r ../rfmix4/bisnp.chr10.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr10.txt -m ../rfmix4/Ref.map --chromosome=10 -o Goroka.chr10 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Goroka.chr11.vcf.gz -r ../rfmix4/bisnp.chr11.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr11.txt -m ../rfmix4/Ref.map --chromosome=11 -o Goroka.chr11 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Goroka.chr12.vcf.gz -r ../rfmix4/bisnp.chr12.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr12.txt -m ../rfmix4/Ref.map --chromosome=12 -o Goroka.chr12 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Goroka.chr13.vcf.gz -r ../rfmix4/bisnp.chr13.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr13.txt -m ../rfmix4/Ref.map --chromosome=13 -o Goroka.chr13 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Goroka.chr14.vcf.gz -r ../rfmix4/bisnp.chr14.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr14.txt -m ../rfmix4/Ref.map --chromosome=14 -o Goroka.chr14 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Goroka.chr15.vcf.gz -r ../rfmix4/bisnp.chr15.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr15.txt -m ../rfmix4/Ref.map --chromosome=15 -o Goroka.chr15 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Goroka.chr16.vcf.gz -r ../rfmix4/bisnp.chr16.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr16.txt -m ../rfmix4/Ref.map --chromosome=16 -o Goroka.chr16 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Goroka.chr17.vcf.gz -r ../rfmix4/bisnp.chr17.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr17.txt -m ../rfmix4/Ref.map --chromosome=17 -o Goroka.chr17 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Goroka.chr18.vcf.gz -r ../rfmix4/bisnp.chr18.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr18.txt -m ../rfmix4/Ref.map --chromosome=18 -o Goroka.chr18 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Goroka.chr19.vcf.gz -r ../rfmix4/bisnp.chr19.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr19.txt -m ../rfmix4/Ref.map --chromosome=19 -o Goroka.chr19 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Goroka.chr20.vcf.gz -r ../rfmix4/bisnp.chr20.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr20.txt -m ../rfmix4/Ref.map --chromosome=20 -o Goroka.chr20 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Goroka.chr21.vcf.gz -r ../rfmix4/bisnp.chr21.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr21.txt -m ../rfmix4/Ref.map --chromosome=21 -o Goroka.chr21 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Goroka.chr22.vcf.gz -r ../rfmix4/bisnp.chr22.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr22.txt -m ../rfmix4/Ref.map --chromosome=22 -o Goroka.chr22 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Kove.chr1.vcf.gz -r ../rfmix4/bisnp.chr1.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr1.txt -m ../rfmix4/Ref.map --chromosome=1 -o Kove.chr1 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Kove.chr2.vcf.gz -r ../rfmix4/bisnp.chr2.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr2.txt -m ../rfmix4/Ref.map --chromosome=2 -o Kove.chr2 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Kove.chr3.vcf.gz -r ../rfmix4/bisnp.chr3.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr3.txt -m ../rfmix4/Ref.map --chromosome=3 -o Kove.chr3 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Kove.chr4.vcf.gz -r ../rfmix4/bisnp.chr4.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr4.txt -m ../rfmix4/Ref.map --chromosome=4 -o Kove.chr4 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Kove.chr5.vcf.gz -r ../rfmix4/bisnp.chr5.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr5.txt -m ../rfmix4/Ref.map --chromosome=5 -o Kove.chr5 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Kove.chr6.vcf.gz -r ../rfmix4/bisnp.chr6.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr6.txt -m ../rfmix4/Ref.map --chromosome=6 -o Kove.chr6 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Kove.chr7.vcf.gz -r ../rfmix4/bisnp.chr7.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr7.txt -m ../rfmix4/Ref.map --chromosome=7 -o Kove.chr7 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Kove.chr8.vcf.gz -r ../rfmix4/bisnp.chr8.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr8.txt -m ../rfmix4/Ref.map --chromosome=8 -o Kove.chr8 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Kove.chr9.vcf.gz -r ../rfmix4/bisnp.chr9.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr9.txt -m ../rfmix4/Ref.map --chromosome=9 -o Kove.chr9 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Kove.chr10.vcf.gz -r ../rfmix4/bisnp.chr10.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr10.txt -m ../rfmix4/Ref.map --chromosome=10 -o Kove.chr10 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Kove.chr11.vcf.gz -r ../rfmix4/bisnp.chr11.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr11.txt -m ../rfmix4/Ref.map --chromosome=11 -o Kove.chr11 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Kove.chr12.vcf.gz -r ../rfmix4/bisnp.chr12.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr12.txt -m ../rfmix4/Ref.map --chromosome=12 -o Kove.chr12 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Kove.chr13.vcf.gz -r ../rfmix4/bisnp.chr13.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr13.txt -m ../rfmix4/Ref.map --chromosome=13 -o Kove.chr13 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Kove.chr14.vcf.gz -r ../rfmix4/bisnp.chr14.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr14.txt -m ../rfmix4/Ref.map --chromosome=14 -o Kove.chr14 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Kove.chr15.vcf.gz -r ../rfmix4/bisnp.chr15.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr15.txt -m ../rfmix4/Ref.map --chromosome=15 -o Kove.chr15 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Kove.chr16.vcf.gz -r ../rfmix4/bisnp.chr16.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr16.txt -m ../rfmix4/Ref.map --chromosome=16 -o Kove.chr16 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Kove.chr17.vcf.gz -r ../rfmix4/bisnp.chr17.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr17.txt -m ../rfmix4/Ref.map --chromosome=17 -o Kove.chr17 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Kove.chr18.vcf.gz -r ../rfmix4/bisnp.chr18.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr18.txt -m ../rfmix4/Ref.map --chromosome=18 -o Kove.chr18 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Kove.chr19.vcf.gz -r ../rfmix4/bisnp.chr19.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr19.txt -m ../rfmix4/Ref.map --chromosome=19 -o Kove.chr19 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Kove.chr20.vcf.gz -r ../rfmix4/bisnp.chr20.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr20.txt -m ../rfmix4/Ref.map --chromosome=20 -o Kove.chr20 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Kove.chr21.vcf.gz -r ../rfmix4/bisnp.chr21.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr21.txt -m ../rfmix4/Ref.map --chromosome=21 -o Kove.chr21 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Kove.chr22.vcf.gz -r ../rfmix4/bisnp.chr22.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr22.txt -m ../rfmix4/Ref.map --chromosome=22 -o Kove.chr22 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Lavongai-Mussau.chr1.vcf.gz -r ../rfmix4/bisnp.chr1.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr1.txt -m ../rfmix4/Ref.map --chromosome=1 -o Lavongai-Mussau.chr1 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Lavongai-Mussau.chr2.vcf.gz -r ../rfmix4/bisnp.chr2.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr2.txt -m ../rfmix4/Ref.map --chromosome=2 -o Lavongai-Mussau.chr2 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Lavongai-Mussau.chr3.vcf.gz -r ../rfmix4/bisnp.chr3.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr3.txt -m ../rfmix4/Ref.map --chromosome=3 -o Lavongai-Mussau.chr3 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Lavongai-Mussau.chr4.vcf.gz -r ../rfmix4/bisnp.chr4.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr4.txt -m ../rfmix4/Ref.map --chromosome=4 -o Lavongai-Mussau.chr4 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Lavongai-Mussau.chr5.vcf.gz -r ../rfmix4/bisnp.chr5.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr5.txt -m ../rfmix4/Ref.map --chromosome=5 -o Lavongai-Mussau.chr5 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Lavongai-Mussau.chr6.vcf.gz -r ../rfmix4/bisnp.chr6.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr6.txt -m ../rfmix4/Ref.map --chromosome=6 -o Lavongai-Mussau.chr6 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Lavongai-Mussau.chr7.vcf.gz -r ../rfmix4/bisnp.chr7.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr7.txt -m ../rfmix4/Ref.map --chromosome=7 -o Lavongai-Mussau.chr7 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Lavongai-Mussau.chr8.vcf.gz -r ../rfmix4/bisnp.chr8.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr8.txt -m ../rfmix4/Ref.map --chromosome=8 -o Lavongai-Mussau.chr8 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Lavongai-Mussau.chr9.vcf.gz -r ../rfmix4/bisnp.chr9.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr9.txt -m ../rfmix4/Ref.map --chromosome=9 -o Lavongai-Mussau.chr9 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Lavongai-Mussau.chr10.vcf.gz -r ../rfmix4/bisnp.chr10.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr10.txt -m ../rfmix4/Ref.map --chromosome=10 -o Lavongai-Mussau.chr10 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Lavongai-Mussau.chr11.vcf.gz -r ../rfmix4/bisnp.chr11.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr11.txt -m ../rfmix4/Ref.map --chromosome=11 -o Lavongai-Mussau.chr11 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Lavongai-Mussau.chr12.vcf.gz -r ../rfmix4/bisnp.chr12.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr12.txt -m ../rfmix4/Ref.map --chromosome=12 -o Lavongai-Mussau.chr12 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Lavongai-Mussau.chr13.vcf.gz -r ../rfmix4/bisnp.chr13.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr13.txt -m ../rfmix4/Ref.map --chromosome=13 -o Lavongai-Mussau.chr13 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Lavongai-Mussau.chr14.vcf.gz -r ../rfmix4/bisnp.chr14.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr14.txt -m ../rfmix4/Ref.map --chromosome=14 -o Lavongai-Mussau.chr14 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Lavongai-Mussau.chr15.vcf.gz -r ../rfmix4/bisnp.chr15.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr15.txt -m ../rfmix4/Ref.map --chromosome=15 -o Lavongai-Mussau.chr15 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Lavongai-Mussau.chr16.vcf.gz -r ../rfmix4/bisnp.chr16.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr16.txt -m ../rfmix4/Ref.map --chromosome=16 -o Lavongai-Mussau.chr16 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Lavongai-Mussau.chr17.vcf.gz -r ../rfmix4/bisnp.chr17.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr17.txt -m ../rfmix4/Ref.map --chromosome=17 -o Lavongai-Mussau.chr17 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Lavongai-Mussau.chr18.vcf.gz -r ../rfmix4/bisnp.chr18.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr18.txt -m ../rfmix4/Ref.map --chromosome=18 -o Lavongai-Mussau.chr18 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Lavongai-Mussau.chr19.vcf.gz -r ../rfmix4/bisnp.chr19.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr19.txt -m ../rfmix4/Ref.map --chromosome=19 -o Lavongai-Mussau.chr19 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Lavongai-Mussau.chr20.vcf.gz -r ../rfmix4/bisnp.chr20.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr20.txt -m ../rfmix4/Ref.map --chromosome=20 -o Lavongai-Mussau.chr20 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Lavongai-Mussau.chr21.vcf.gz -r ../rfmix4/bisnp.chr21.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr21.txt -m ../rfmix4/Ref.map --chromosome=21 -o Lavongai-Mussau.chr21 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Lavongai-Mussau.chr22.vcf.gz -r ../rfmix4/bisnp.chr22.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr22.txt -m ../rfmix4/Ref.map --chromosome=22 -o Lavongai-Mussau.chr22 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Malaita.chr1.vcf.gz -r ../rfmix4/bisnp.chr1.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr1.txt -m ../rfmix4/Ref.map --chromosome=1 -o Malaita.chr1 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Malaita.chr2.vcf.gz -r ../rfmix4/bisnp.chr2.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr2.txt -m ../rfmix4/Ref.map --chromosome=2 -o Malaita.chr2 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Malaita.chr3.vcf.gz -r ../rfmix4/bisnp.chr3.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr3.txt -m ../rfmix4/Ref.map --chromosome=3 -o Malaita.chr3 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Malaita.chr4.vcf.gz -r ../rfmix4/bisnp.chr4.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr4.txt -m ../rfmix4/Ref.map --chromosome=4 -o Malaita.chr4 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Malaita.chr5.vcf.gz -r ../rfmix4/bisnp.chr5.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr5.txt -m ../rfmix4/Ref.map --chromosome=5 -o Malaita.chr5 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Malaita.chr6.vcf.gz -r ../rfmix4/bisnp.chr6.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr6.txt -m ../rfmix4/Ref.map --chromosome=6 -o Malaita.chr6 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Malaita.chr7.vcf.gz -r ../rfmix4/bisnp.chr7.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr7.txt -m ../rfmix4/Ref.map --chromosome=7 -o Malaita.chr7 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Malaita.chr8.vcf.gz -r ../rfmix4/bisnp.chr8.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr8.txt -m ../rfmix4/Ref.map --chromosome=8 -o Malaita.chr8 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Malaita.chr9.vcf.gz -r ../rfmix4/bisnp.chr9.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr9.txt -m ../rfmix4/Ref.map --chromosome=9 -o Malaita.chr9 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Malaita.chr10.vcf.gz -r ../rfmix4/bisnp.chr10.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr10.txt -m ../rfmix4/Ref.map --chromosome=10 -o Malaita.chr10 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Malaita.chr11.vcf.gz -r ../rfmix4/bisnp.chr11.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr11.txt -m ../rfmix4/Ref.map --chromosome=11 -o Malaita.chr11 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Malaita.chr12.vcf.gz -r ../rfmix4/bisnp.chr12.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr12.txt -m ../rfmix4/Ref.map --chromosome=12 -o Malaita.chr12 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Malaita.chr13.vcf.gz -r ../rfmix4/bisnp.chr13.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr13.txt -m ../rfmix4/Ref.map --chromosome=13 -o Malaita.chr13 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Malaita.chr14.vcf.gz -r ../rfmix4/bisnp.chr14.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr14.txt -m ../rfmix4/Ref.map --chromosome=14 -o Malaita.chr14 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Malaita.chr15.vcf.gz -r ../rfmix4/bisnp.chr15.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr15.txt -m ../rfmix4/Ref.map --chromosome=15 -o Malaita.chr15 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Malaita.chr16.vcf.gz -r ../rfmix4/bisnp.chr16.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr16.txt -m ../rfmix4/Ref.map --chromosome=16 -o Malaita.chr16 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Malaita.chr17.vcf.gz -r ../rfmix4/bisnp.chr17.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr17.txt -m ../rfmix4/Ref.map --chromosome=17 -o Malaita.chr17 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Malaita.chr18.vcf.gz -r ../rfmix4/bisnp.chr18.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr18.txt -m ../rfmix4/Ref.map --chromosome=18 -o Malaita.chr18 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Malaita.chr19.vcf.gz -r ../rfmix4/bisnp.chr19.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr19.txt -m ../rfmix4/Ref.map --chromosome=19 -o Malaita.chr19 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Malaita.chr20.vcf.gz -r ../rfmix4/bisnp.chr20.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr20.txt -m ../rfmix4/Ref.map --chromosome=20 -o Malaita.chr20 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Malaita.chr21.vcf.gz -r ../rfmix4/bisnp.chr21.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr21.txt -m ../rfmix4/Ref.map --chromosome=21 -o Malaita.chr21 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Malaita.chr22.vcf.gz -r ../rfmix4/bisnp.chr22.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr22.txt -m ../rfmix4/Ref.map --chromosome=22 -o Malaita.chr22 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Mamusi.chr1.vcf.gz -r ../rfmix4/bisnp.chr1.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr1.txt -m ../rfmix4/Ref.map --chromosome=1 -o Mamusi.chr1 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Mamusi.chr2.vcf.gz -r ../rfmix4/bisnp.chr2.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr2.txt -m ../rfmix4/Ref.map --chromosome=2 -o Mamusi.chr2 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Mamusi.chr3.vcf.gz -r ../rfmix4/bisnp.chr3.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr3.txt -m ../rfmix4/Ref.map --chromosome=3 -o Mamusi.chr3 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Mamusi.chr4.vcf.gz -r ../rfmix4/bisnp.chr4.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr4.txt -m ../rfmix4/Ref.map --chromosome=4 -o Mamusi.chr4 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Mamusi.chr5.vcf.gz -r ../rfmix4/bisnp.chr5.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr5.txt -m ../rfmix4/Ref.map --chromosome=5 -o Mamusi.chr5 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Mamusi.chr6.vcf.gz -r ../rfmix4/bisnp.chr6.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr6.txt -m ../rfmix4/Ref.map --chromosome=6 -o Mamusi.chr6 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Mamusi.chr7.vcf.gz -r ../rfmix4/bisnp.chr7.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr7.txt -m ../rfmix4/Ref.map --chromosome=7 -o Mamusi.chr7 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Mamusi.chr8.vcf.gz -r ../rfmix4/bisnp.chr8.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr8.txt -m ../rfmix4/Ref.map --chromosome=8 -o Mamusi.chr8 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Mamusi.chr9.vcf.gz -r ../rfmix4/bisnp.chr9.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr9.txt -m ../rfmix4/Ref.map --chromosome=9 -o Mamusi.chr9 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Mamusi.chr10.vcf.gz -r ../rfmix4/bisnp.chr10.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr10.txt -m ../rfmix4/Ref.map --chromosome=10 -o Mamusi.chr10 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Mamusi.chr11.vcf.gz -r ../rfmix4/bisnp.chr11.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr11.txt -m ../rfmix4/Ref.map --chromosome=11 -o Mamusi.chr11 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Mamusi.chr12.vcf.gz -r ../rfmix4/bisnp.chr12.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr12.txt -m ../rfmix4/Ref.map --chromosome=12 -o Mamusi.chr12 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Mamusi.chr13.vcf.gz -r ../rfmix4/bisnp.chr13.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr13.txt -m ../rfmix4/Ref.map --chromosome=13 -o Mamusi.chr13 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Mamusi.chr14.vcf.gz -r ../rfmix4/bisnp.chr14.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr14.txt -m ../rfmix4/Ref.map --chromosome=14 -o Mamusi.chr14 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Mamusi.chr15.vcf.gz -r ../rfmix4/bisnp.chr15.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr15.txt -m ../rfmix4/Ref.map --chromosome=15 -o Mamusi.chr15 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Mamusi.chr16.vcf.gz -r ../rfmix4/bisnp.chr16.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr16.txt -m ../rfmix4/Ref.map --chromosome=16 -o Mamusi.chr16 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Mamusi.chr17.vcf.gz -r ../rfmix4/bisnp.chr17.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr17.txt -m ../rfmix4/Ref.map --chromosome=17 -o Mamusi.chr17 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Mamusi.chr18.vcf.gz -r ../rfmix4/bisnp.chr18.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr18.txt -m ../rfmix4/Ref.map --chromosome=18 -o Mamusi.chr18 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Mamusi.chr19.vcf.gz -r ../rfmix4/bisnp.chr19.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr19.txt -m ../rfmix4/Ref.map --chromosome=19 -o Mamusi.chr19 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Mamusi.chr20.vcf.gz -r ../rfmix4/bisnp.chr20.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr20.txt -m ../rfmix4/Ref.map --chromosome=20 -o Mamusi.chr20 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Mamusi.chr21.vcf.gz -r ../rfmix4/bisnp.chr21.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr21.txt -m ../rfmix4/Ref.map --chromosome=21 -o Mamusi.chr21 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Mamusi.chr22.vcf.gz -r ../rfmix4/bisnp.chr22.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr22.txt -m ../rfmix4/Ref.map --chromosome=22 -o Mamusi.chr22 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Mangseng.chr1.vcf.gz -r ../rfmix4/bisnp.chr1.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr1.txt -m ../rfmix4/Ref.map --chromosome=1 -o Mangseng.chr1 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Mangseng.chr2.vcf.gz -r ../rfmix4/bisnp.chr2.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr2.txt -m ../rfmix4/Ref.map --chromosome=2 -o Mangseng.chr2 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Mangseng.chr3.vcf.gz -r ../rfmix4/bisnp.chr3.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr3.txt -m ../rfmix4/Ref.map --chromosome=3 -o Mangseng.chr3 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Mangseng.chr4.vcf.gz -r ../rfmix4/bisnp.chr4.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr4.txt -m ../rfmix4/Ref.map --chromosome=4 -o Mangseng.chr4 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Mangseng.chr5.vcf.gz -r ../rfmix4/bisnp.chr5.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr5.txt -m ../rfmix4/Ref.map --chromosome=5 -o Mangseng.chr5 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Mangseng.chr6.vcf.gz -r ../rfmix4/bisnp.chr6.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr6.txt -m ../rfmix4/Ref.map --chromosome=6 -o Mangseng.chr6 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Mangseng.chr7.vcf.gz -r ../rfmix4/bisnp.chr7.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr7.txt -m ../rfmix4/Ref.map --chromosome=7 -o Mangseng.chr7 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Mangseng.chr8.vcf.gz -r ../rfmix4/bisnp.chr8.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr8.txt -m ../rfmix4/Ref.map --chromosome=8 -o Mangseng.chr8 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Mangseng.chr9.vcf.gz -r ../rfmix4/bisnp.chr9.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr9.txt -m ../rfmix4/Ref.map --chromosome=9 -o Mangseng.chr9 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Mangseng.chr10.vcf.gz -r ../rfmix4/bisnp.chr10.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr10.txt -m ../rfmix4/Ref.map --chromosome=10 -o Mangseng.chr10 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Mangseng.chr11.vcf.gz -r ../rfmix4/bisnp.chr11.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr11.txt -m ../rfmix4/Ref.map --chromosome=11 -o Mangseng.chr11 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Mangseng.chr12.vcf.gz -r ../rfmix4/bisnp.chr12.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr12.txt -m ../rfmix4/Ref.map --chromosome=12 -o Mangseng.chr12 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Mangseng.chr13.vcf.gz -r ../rfmix4/bisnp.chr13.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr13.txt -m ../rfmix4/Ref.map --chromosome=13 -o Mangseng.chr13 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Mangseng.chr14.vcf.gz -r ../rfmix4/bisnp.chr14.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr14.txt -m ../rfmix4/Ref.map --chromosome=14 -o Mangseng.chr14 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Mangseng.chr15.vcf.gz -r ../rfmix4/bisnp.chr15.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr15.txt -m ../rfmix4/Ref.map --chromosome=15 -o Mangseng.chr15 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Mangseng.chr16.vcf.gz -r ../rfmix4/bisnp.chr16.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr16.txt -m ../rfmix4/Ref.map --chromosome=16 -o Mangseng.chr16 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Mangseng.chr17.vcf.gz -r ../rfmix4/bisnp.chr17.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr17.txt -m ../rfmix4/Ref.map --chromosome=17 -o Mangseng.chr17 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Mangseng.chr18.vcf.gz -r ../rfmix4/bisnp.chr18.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr18.txt -m ../rfmix4/Ref.map --chromosome=18 -o Mangseng.chr18 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Mangseng.chr19.vcf.gz -r ../rfmix4/bisnp.chr19.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr19.txt -m ../rfmix4/Ref.map --chromosome=19 -o Mangseng.chr19 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Mangseng.chr20.vcf.gz -r ../rfmix4/bisnp.chr20.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr20.txt -m ../rfmix4/Ref.map --chromosome=20 -o Mangseng.chr20 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Mangseng.chr21.vcf.gz -r ../rfmix4/bisnp.chr21.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr21.txt -m ../rfmix4/Ref.map --chromosome=21 -o Mangseng.chr21 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Mangseng.chr22.vcf.gz -r ../rfmix4/bisnp.chr22.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr22.txt -m ../rfmix4/Ref.map --chromosome=22 -o Mangseng.chr22 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Melamela.chr1.vcf.gz -r ../rfmix4/bisnp.chr1.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr1.txt -m ../rfmix4/Ref.map --chromosome=1 -o Melamela.chr1 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Melamela.chr2.vcf.gz -r ../rfmix4/bisnp.chr2.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr2.txt -m ../rfmix4/Ref.map --chromosome=2 -o Melamela.chr2 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Melamela.chr3.vcf.gz -r ../rfmix4/bisnp.chr3.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr3.txt -m ../rfmix4/Ref.map --chromosome=3 -o Melamela.chr3 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Melamela.chr4.vcf.gz -r ../rfmix4/bisnp.chr4.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr4.txt -m ../rfmix4/Ref.map --chromosome=4 -o Melamela.chr4 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Melamela.chr5.vcf.gz -r ../rfmix4/bisnp.chr5.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr5.txt -m ../rfmix4/Ref.map --chromosome=5 -o Melamela.chr5 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Melamela.chr6.vcf.gz -r ../rfmix4/bisnp.chr6.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr6.txt -m ../rfmix4/Ref.map --chromosome=6 -o Melamela.chr6 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Melamela.chr7.vcf.gz -r ../rfmix4/bisnp.chr7.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr7.txt -m ../rfmix4/Ref.map --chromosome=7 -o Melamela.chr7 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Melamela.chr8.vcf.gz -r ../rfmix4/bisnp.chr8.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr8.txt -m ../rfmix4/Ref.map --chromosome=8 -o Melamela.chr8 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Melamela.chr9.vcf.gz -r ../rfmix4/bisnp.chr9.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr9.txt -m ../rfmix4/Ref.map --chromosome=9 -o Melamela.chr9 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Melamela.chr10.vcf.gz -r ../rfmix4/bisnp.chr10.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr10.txt -m ../rfmix4/Ref.map --chromosome=10 -o Melamela.chr10 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Melamela.chr11.vcf.gz -r ../rfmix4/bisnp.chr11.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr11.txt -m ../rfmix4/Ref.map --chromosome=11 -o Melamela.chr11 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Melamela.chr12.vcf.gz -r ../rfmix4/bisnp.chr12.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr12.txt -m ../rfmix4/Ref.map --chromosome=12 -o Melamela.chr12 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Melamela.chr13.vcf.gz -r ../rfmix4/bisnp.chr13.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr13.txt -m ../rfmix4/Ref.map --chromosome=13 -o Melamela.chr13 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Melamela.chr14.vcf.gz -r ../rfmix4/bisnp.chr14.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr14.txt -m ../rfmix4/Ref.map --chromosome=14 -o Melamela.chr14 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Melamela.chr15.vcf.gz -r ../rfmix4/bisnp.chr15.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr15.txt -m ../rfmix4/Ref.map --chromosome=15 -o Melamela.chr15 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Melamela.chr16.vcf.gz -r ../rfmix4/bisnp.chr16.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr16.txt -m ../rfmix4/Ref.map --chromosome=16 -o Melamela.chr16 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Melamela.chr17.vcf.gz -r ../rfmix4/bisnp.chr17.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr17.txt -m ../rfmix4/Ref.map --chromosome=17 -o Melamela.chr17 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Melamela.chr18.vcf.gz -r ../rfmix4/bisnp.chr18.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr18.txt -m ../rfmix4/Ref.map --chromosome=18 -o Melamela.chr18 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Melamela.chr19.vcf.gz -r ../rfmix4/bisnp.chr19.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr19.txt -m ../rfmix4/Ref.map --chromosome=19 -o Melamela.chr19 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Melamela.chr20.vcf.gz -r ../rfmix4/bisnp.chr20.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr20.txt -m ../rfmix4/Ref.map --chromosome=20 -o Melamela.chr20 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Melamela.chr21.vcf.gz -r ../rfmix4/bisnp.chr21.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr21.txt -m ../rfmix4/Ref.map --chromosome=21 -o Melamela.chr21 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Melamela.chr22.vcf.gz -r ../rfmix4/bisnp.chr22.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr22.txt -m ../rfmix4/Ref.map --chromosome=22 -o Melamela.chr22 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Nailik-Notsi-Tigak.chr1.vcf.gz -r ../rfmix4/bisnp.chr1.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr1.txt -m ../rfmix4/Ref.map --chromosome=1 -o Nailik-Notsi-Tigak.chr1 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Nailik-Notsi-Tigak.chr2.vcf.gz -r ../rfmix4/bisnp.chr2.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr2.txt -m ../rfmix4/Ref.map --chromosome=2 -o Nailik-Notsi-Tigak.chr2 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Nailik-Notsi-Tigak.chr3.vcf.gz -r ../rfmix4/bisnp.chr3.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr3.txt -m ../rfmix4/Ref.map --chromosome=3 -o Nailik-Notsi-Tigak.chr3 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Nailik-Notsi-Tigak.chr4.vcf.gz -r ../rfmix4/bisnp.chr4.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr4.txt -m ../rfmix4/Ref.map --chromosome=4 -o Nailik-Notsi-Tigak.chr4 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Nailik-Notsi-Tigak.chr5.vcf.gz -r ../rfmix4/bisnp.chr5.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr5.txt -m ../rfmix4/Ref.map --chromosome=5 -o Nailik-Notsi-Tigak.chr5 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Nailik-Notsi-Tigak.chr6.vcf.gz -r ../rfmix4/bisnp.chr6.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr6.txt -m ../rfmix4/Ref.map --chromosome=6 -o Nailik-Notsi-Tigak.chr6 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Nailik-Notsi-Tigak.chr7.vcf.gz -r ../rfmix4/bisnp.chr7.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr7.txt -m ../rfmix4/Ref.map --chromosome=7 -o Nailik-Notsi-Tigak.chr7 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Nailik-Notsi-Tigak.chr8.vcf.gz -r ../rfmix4/bisnp.chr8.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr8.txt -m ../rfmix4/Ref.map --chromosome=8 -o Nailik-Notsi-Tigak.chr8 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Nailik-Notsi-Tigak.chr9.vcf.gz -r ../rfmix4/bisnp.chr9.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr9.txt -m ../rfmix4/Ref.map --chromosome=9 -o Nailik-Notsi-Tigak.chr9 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Nailik-Notsi-Tigak.chr10.vcf.gz -r ../rfmix4/bisnp.chr10.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr10.txt -m ../rfmix4/Ref.map --chromosome=10 -o Nailik-Notsi-Tigak.chr10 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Nailik-Notsi-Tigak.chr11.vcf.gz -r ../rfmix4/bisnp.chr11.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr11.txt -m ../rfmix4/Ref.map --chromosome=11 -o Nailik-Notsi-Tigak.chr11 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Nailik-Notsi-Tigak.chr12.vcf.gz -r ../rfmix4/bisnp.chr12.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr12.txt -m ../rfmix4/Ref.map --chromosome=12 -o Nailik-Notsi-Tigak.chr12 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Nailik-Notsi-Tigak.chr13.vcf.gz -r ../rfmix4/bisnp.chr13.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr13.txt -m ../rfmix4/Ref.map --chromosome=13 -o Nailik-Notsi-Tigak.chr13 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Nailik-Notsi-Tigak.chr14.vcf.gz -r ../rfmix4/bisnp.chr14.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr14.txt -m ../rfmix4/Ref.map --chromosome=14 -o Nailik-Notsi-Tigak.chr14 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Nailik-Notsi-Tigak.chr15.vcf.gz -r ../rfmix4/bisnp.chr15.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr15.txt -m ../rfmix4/Ref.map --chromosome=15 -o Nailik-Notsi-Tigak.chr15 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Nailik-Notsi-Tigak.chr16.vcf.gz -r ../rfmix4/bisnp.chr16.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr16.txt -m ../rfmix4/Ref.map --chromosome=16 -o Nailik-Notsi-Tigak.chr16 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Nailik-Notsi-Tigak.chr17.vcf.gz -r ../rfmix4/bisnp.chr17.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr17.txt -m ../rfmix4/Ref.map --chromosome=17 -o Nailik-Notsi-Tigak.chr17 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Nailik-Notsi-Tigak.chr18.vcf.gz -r ../rfmix4/bisnp.chr18.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr18.txt -m ../rfmix4/Ref.map --chromosome=18 -o Nailik-Notsi-Tigak.chr18 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Nailik-Notsi-Tigak.chr19.vcf.gz -r ../rfmix4/bisnp.chr19.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr19.txt -m ../rfmix4/Ref.map --chromosome=19 -o Nailik-Notsi-Tigak.chr19 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Nailik-Notsi-Tigak.chr20.vcf.gz -r ../rfmix4/bisnp.chr20.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr20.txt -m ../rfmix4/Ref.map --chromosome=20 -o Nailik-Notsi-Tigak.chr20 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Nailik-Notsi-Tigak.chr21.vcf.gz -r ../rfmix4/bisnp.chr21.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr21.txt -m ../rfmix4/Ref.map --chromosome=21 -o Nailik-Notsi-Tigak.chr21 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Nailik-Notsi-Tigak.chr22.vcf.gz -r ../rfmix4/bisnp.chr22.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr22.txt -m ../rfmix4/Ref.map --chromosome=22 -o Nailik-Notsi-Tigak.chr22 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Nakanai.chr1.vcf.gz -r ../rfmix4/bisnp.chr1.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr1.txt -m ../rfmix4/Ref.map --chromosome=1 -o Nakanai.chr1 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Nakanai.chr2.vcf.gz -r ../rfmix4/bisnp.chr2.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr2.txt -m ../rfmix4/Ref.map --chromosome=2 -o Nakanai.chr2 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Nakanai.chr3.vcf.gz -r ../rfmix4/bisnp.chr3.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr3.txt -m ../rfmix4/Ref.map --chromosome=3 -o Nakanai.chr3 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Nakanai.chr4.vcf.gz -r ../rfmix4/bisnp.chr4.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr4.txt -m ../rfmix4/Ref.map --chromosome=4 -o Nakanai.chr4 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Nakanai.chr5.vcf.gz -r ../rfmix4/bisnp.chr5.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr5.txt -m ../rfmix4/Ref.map --chromosome=5 -o Nakanai.chr5 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Nakanai.chr6.vcf.gz -r ../rfmix4/bisnp.chr6.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr6.txt -m ../rfmix4/Ref.map --chromosome=6 -o Nakanai.chr6 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Nakanai.chr7.vcf.gz -r ../rfmix4/bisnp.chr7.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr7.txt -m ../rfmix4/Ref.map --chromosome=7 -o Nakanai.chr7 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Nakanai.chr8.vcf.gz -r ../rfmix4/bisnp.chr8.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr8.txt -m ../rfmix4/Ref.map --chromosome=8 -o Nakanai.chr8 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Nakanai.chr9.vcf.gz -r ../rfmix4/bisnp.chr9.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr9.txt -m ../rfmix4/Ref.map --chromosome=9 -o Nakanai.chr9 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Nakanai.chr10.vcf.gz -r ../rfmix4/bisnp.chr10.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr10.txt -m ../rfmix4/Ref.map --chromosome=10 -o Nakanai.chr10 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Nakanai.chr11.vcf.gz -r ../rfmix4/bisnp.chr11.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr11.txt -m ../rfmix4/Ref.map --chromosome=11 -o Nakanai.chr11 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Nakanai.chr12.vcf.gz -r ../rfmix4/bisnp.chr12.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr12.txt -m ../rfmix4/Ref.map --chromosome=12 -o Nakanai.chr12 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Nakanai.chr13.vcf.gz -r ../rfmix4/bisnp.chr13.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr13.txt -m ../rfmix4/Ref.map --chromosome=13 -o Nakanai.chr13 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Nakanai.chr14.vcf.gz -r ../rfmix4/bisnp.chr14.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr14.txt -m ../rfmix4/Ref.map --chromosome=14 -o Nakanai.chr14 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Nakanai.chr15.vcf.gz -r ../rfmix4/bisnp.chr15.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr15.txt -m ../rfmix4/Ref.map --chromosome=15 -o Nakanai.chr15 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Nakanai.chr16.vcf.gz -r ../rfmix4/bisnp.chr16.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr16.txt -m ../rfmix4/Ref.map --chromosome=16 -o Nakanai.chr16 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Nakanai.chr17.vcf.gz -r ../rfmix4/bisnp.chr17.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr17.txt -m ../rfmix4/Ref.map --chromosome=17 -o Nakanai.chr17 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Nakanai.chr18.vcf.gz -r ../rfmix4/bisnp.chr18.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr18.txt -m ../rfmix4/Ref.map --chromosome=18 -o Nakanai.chr18 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Nakanai.chr19.vcf.gz -r ../rfmix4/bisnp.chr19.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr19.txt -m ../rfmix4/Ref.map --chromosome=19 -o Nakanai.chr19 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Nakanai.chr20.vcf.gz -r ../rfmix4/bisnp.chr20.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr20.txt -m ../rfmix4/Ref.map --chromosome=20 -o Nakanai.chr20 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Nakanai.chr21.vcf.gz -r ../rfmix4/bisnp.chr21.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr21.txt -m ../rfmix4/Ref.map --chromosome=21 -o Nakanai.chr21 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Nakanai.chr22.vcf.gz -r ../rfmix4/bisnp.chr22.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr22.txt -m ../rfmix4/Ref.map --chromosome=22 -o Nakanai.chr22 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Nasioi.chr1.vcf.gz -r ../rfmix4/bisnp.chr1.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr1.txt -m ../rfmix4/Ref.map --chromosome=1 -o Nasioi.chr1 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Nasioi.chr2.vcf.gz -r ../rfmix4/bisnp.chr2.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr2.txt -m ../rfmix4/Ref.map --chromosome=2 -o Nasioi.chr2 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Nasioi.chr3.vcf.gz -r ../rfmix4/bisnp.chr3.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr3.txt -m ../rfmix4/Ref.map --chromosome=3 -o Nasioi.chr3 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Nasioi.chr4.vcf.gz -r ../rfmix4/bisnp.chr4.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr4.txt -m ../rfmix4/Ref.map --chromosome=4 -o Nasioi.chr4 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Nasioi.chr5.vcf.gz -r ../rfmix4/bisnp.chr5.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr5.txt -m ../rfmix4/Ref.map --chromosome=5 -o Nasioi.chr5 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Nasioi.chr6.vcf.gz -r ../rfmix4/bisnp.chr6.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr6.txt -m ../rfmix4/Ref.map --chromosome=6 -o Nasioi.chr6 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Nasioi.chr7.vcf.gz -r ../rfmix4/bisnp.chr7.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr7.txt -m ../rfmix4/Ref.map --chromosome=7 -o Nasioi.chr7 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Nasioi.chr8.vcf.gz -r ../rfmix4/bisnp.chr8.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr8.txt -m ../rfmix4/Ref.map --chromosome=8 -o Nasioi.chr8 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Nasioi.chr9.vcf.gz -r ../rfmix4/bisnp.chr9.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr9.txt -m ../rfmix4/Ref.map --chromosome=9 -o Nasioi.chr9 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Nasioi.chr10.vcf.gz -r ../rfmix4/bisnp.chr10.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr10.txt -m ../rfmix4/Ref.map --chromosome=10 -o Nasioi.chr10 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Nasioi.chr11.vcf.gz -r ../rfmix4/bisnp.chr11.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr11.txt -m ../rfmix4/Ref.map --chromosome=11 -o Nasioi.chr11 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Nasioi.chr12.vcf.gz -r ../rfmix4/bisnp.chr12.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr12.txt -m ../rfmix4/Ref.map --chromosome=12 -o Nasioi.chr12 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Nasioi.chr13.vcf.gz -r ../rfmix4/bisnp.chr13.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr13.txt -m ../rfmix4/Ref.map --chromosome=13 -o Nasioi.chr13 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Nasioi.chr14.vcf.gz -r ../rfmix4/bisnp.chr14.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr14.txt -m ../rfmix4/Ref.map --chromosome=14 -o Nasioi.chr14 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Nasioi.chr15.vcf.gz -r ../rfmix4/bisnp.chr15.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr15.txt -m ../rfmix4/Ref.map --chromosome=15 -o Nasioi.chr15 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Nasioi.chr16.vcf.gz -r ../rfmix4/bisnp.chr16.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr16.txt -m ../rfmix4/Ref.map --chromosome=16 -o Nasioi.chr16 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Nasioi.chr17.vcf.gz -r ../rfmix4/bisnp.chr17.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr17.txt -m ../rfmix4/Ref.map --chromosome=17 -o Nasioi.chr17 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Nasioi.chr18.vcf.gz -r ../rfmix4/bisnp.chr18.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr18.txt -m ../rfmix4/Ref.map --chromosome=18 -o Nasioi.chr18 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Nasioi.chr19.vcf.gz -r ../rfmix4/bisnp.chr19.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr19.txt -m ../rfmix4/Ref.map --chromosome=19 -o Nasioi.chr19 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Nasioi.chr20.vcf.gz -r ../rfmix4/bisnp.chr20.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr20.txt -m ../rfmix4/Ref.map --chromosome=20 -o Nasioi.chr20 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Nasioi.chr21.vcf.gz -r ../rfmix4/bisnp.chr21.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr21.txt -m ../rfmix4/Ref.map --chromosome=21 -o Nasioi.chr21 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Nasioi.chr22.vcf.gz -r ../rfmix4/bisnp.chr22.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr22.txt -m ../rfmix4/Ref.map --chromosome=22 -o Nasioi.chr22 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Rampasasa.chr1.vcf.gz -r ../rfmix4/bisnp.chr1.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr1.txt -m ../rfmix4/Ref.map --chromosome=1 -o Rampasasa.chr1 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Rampasasa.chr2.vcf.gz -r ../rfmix4/bisnp.chr2.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr2.txt -m ../rfmix4/Ref.map --chromosome=2 -o Rampasasa.chr2 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Rampasasa.chr3.vcf.gz -r ../rfmix4/bisnp.chr3.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr3.txt -m ../rfmix4/Ref.map --chromosome=3 -o Rampasasa.chr3 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Rampasasa.chr4.vcf.gz -r ../rfmix4/bisnp.chr4.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr4.txt -m ../rfmix4/Ref.map --chromosome=4 -o Rampasasa.chr4 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Rampasasa.chr5.vcf.gz -r ../rfmix4/bisnp.chr5.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr5.txt -m ../rfmix4/Ref.map --chromosome=5 -o Rampasasa.chr5 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Rampasasa.chr6.vcf.gz -r ../rfmix4/bisnp.chr6.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr6.txt -m ../rfmix4/Ref.map --chromosome=6 -o Rampasasa.chr6 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Rampasasa.chr7.vcf.gz -r ../rfmix4/bisnp.chr7.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr7.txt -m ../rfmix4/Ref.map --chromosome=7 -o Rampasasa.chr7 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Rampasasa.chr8.vcf.gz -r ../rfmix4/bisnp.chr8.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr8.txt -m ../rfmix4/Ref.map --chromosome=8 -o Rampasasa.chr8 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Rampasasa.chr9.vcf.gz -r ../rfmix4/bisnp.chr9.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr9.txt -m ../rfmix4/Ref.map --chromosome=9 -o Rampasasa.chr9 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Rampasasa.chr10.vcf.gz -r ../rfmix4/bisnp.chr10.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr10.txt -m ../rfmix4/Ref.map --chromosome=10 -o Rampasasa.chr10 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Rampasasa.chr11.vcf.gz -r ../rfmix4/bisnp.chr11.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr11.txt -m ../rfmix4/Ref.map --chromosome=11 -o Rampasasa.chr11 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Rampasasa.chr12.vcf.gz -r ../rfmix4/bisnp.chr12.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr12.txt -m ../rfmix4/Ref.map --chromosome=12 -o Rampasasa.chr12 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Rampasasa.chr13.vcf.gz -r ../rfmix4/bisnp.chr13.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr13.txt -m ../rfmix4/Ref.map --chromosome=13 -o Rampasasa.chr13 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Rampasasa.chr14.vcf.gz -r ../rfmix4/bisnp.chr14.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr14.txt -m ../rfmix4/Ref.map --chromosome=14 -o Rampasasa.chr14 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Rampasasa.chr15.vcf.gz -r ../rfmix4/bisnp.chr15.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr15.txt -m ../rfmix4/Ref.map --chromosome=15 -o Rampasasa.chr15 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Rampasasa.chr16.vcf.gz -r ../rfmix4/bisnp.chr16.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr16.txt -m ../rfmix4/Ref.map --chromosome=16 -o Rampasasa.chr16 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Rampasasa.chr17.vcf.gz -r ../rfmix4/bisnp.chr17.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr17.txt -m ../rfmix4/Ref.map --chromosome=17 -o Rampasasa.chr17 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Rampasasa.chr18.vcf.gz -r ../rfmix4/bisnp.chr18.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr18.txt -m ../rfmix4/Ref.map --chromosome=18 -o Rampasasa.chr18 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Rampasasa.chr19.vcf.gz -r ../rfmix4/bisnp.chr19.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr19.txt -m ../rfmix4/Ref.map --chromosome=19 -o Rampasasa.chr19 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Rampasasa.chr20.vcf.gz -r ../rfmix4/bisnp.chr20.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr20.txt -m ../rfmix4/Ref.map --chromosome=20 -o Rampasasa.chr20 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Rampasasa.chr21.vcf.gz -r ../rfmix4/bisnp.chr21.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr21.txt -m ../rfmix4/Ref.map --chromosome=21 -o Rampasasa.chr21 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Rampasasa.chr22.vcf.gz -r ../rfmix4/bisnp.chr22.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr22.txt -m ../rfmix4/Ref.map --chromosome=22 -o Rampasasa.chr22 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Rennell.chr1.vcf.gz -r ../rfmix4/bisnp.chr1.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr1.txt -m ../rfmix4/Ref.map --chromosome=1 -o Rennell.chr1 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Rennell.chr2.vcf.gz -r ../rfmix4/bisnp.chr2.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr2.txt -m ../rfmix4/Ref.map --chromosome=2 -o Rennell.chr2 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Rennell.chr3.vcf.gz -r ../rfmix4/bisnp.chr3.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr3.txt -m ../rfmix4/Ref.map --chromosome=3 -o Rennell.chr3 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Rennell.chr4.vcf.gz -r ../rfmix4/bisnp.chr4.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr4.txt -m ../rfmix4/Ref.map --chromosome=4 -o Rennell.chr4 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Rennell.chr5.vcf.gz -r ../rfmix4/bisnp.chr5.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr5.txt -m ../rfmix4/Ref.map --chromosome=5 -o Rennell.chr5 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Rennell.chr6.vcf.gz -r ../rfmix4/bisnp.chr6.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr6.txt -m ../rfmix4/Ref.map --chromosome=6 -o Rennell.chr6 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Rennell.chr7.vcf.gz -r ../rfmix4/bisnp.chr7.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr7.txt -m ../rfmix4/Ref.map --chromosome=7 -o Rennell.chr7 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Rennell.chr8.vcf.gz -r ../rfmix4/bisnp.chr8.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr8.txt -m ../rfmix4/Ref.map --chromosome=8 -o Rennell.chr8 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Rennell.chr9.vcf.gz -r ../rfmix4/bisnp.chr9.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr9.txt -m ../rfmix4/Ref.map --chromosome=9 -o Rennell.chr9 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Rennell.chr10.vcf.gz -r ../rfmix4/bisnp.chr10.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr10.txt -m ../rfmix4/Ref.map --chromosome=10 -o Rennell.chr10 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Rennell.chr11.vcf.gz -r ../rfmix4/bisnp.chr11.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr11.txt -m ../rfmix4/Ref.map --chromosome=11 -o Rennell.chr11 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Rennell.chr12.vcf.gz -r ../rfmix4/bisnp.chr12.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr12.txt -m ../rfmix4/Ref.map --chromosome=12 -o Rennell.chr12 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Rennell.chr13.vcf.gz -r ../rfmix4/bisnp.chr13.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr13.txt -m ../rfmix4/Ref.map --chromosome=13 -o Rennell.chr13 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Rennell.chr14.vcf.gz -r ../rfmix4/bisnp.chr14.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr14.txt -m ../rfmix4/Ref.map --chromosome=14 -o Rennell.chr14 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Rennell.chr15.vcf.gz -r ../rfmix4/bisnp.chr15.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr15.txt -m ../rfmix4/Ref.map --chromosome=15 -o Rennell.chr15 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Rennell.chr16.vcf.gz -r ../rfmix4/bisnp.chr16.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr16.txt -m ../rfmix4/Ref.map --chromosome=16 -o Rennell.chr16 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Rennell.chr17.vcf.gz -r ../rfmix4/bisnp.chr17.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr17.txt -m ../rfmix4/Ref.map --chromosome=17 -o Rennell.chr17 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Rennell.chr18.vcf.gz -r ../rfmix4/bisnp.chr18.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr18.txt -m ../rfmix4/Ref.map --chromosome=18 -o Rennell.chr18 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Rennell.chr19.vcf.gz -r ../rfmix4/bisnp.chr19.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr19.txt -m ../rfmix4/Ref.map --chromosome=19 -o Rennell.chr19 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Rennell.chr20.vcf.gz -r ../rfmix4/bisnp.chr20.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr20.txt -m ../rfmix4/Ref.map --chromosome=20 -o Rennell.chr20 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Rennell.chr21.vcf.gz -r ../rfmix4/bisnp.chr21.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr21.txt -m ../rfmix4/Ref.map --chromosome=21 -o Rennell.chr21 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Rennell.chr22.vcf.gz -r ../rfmix4/bisnp.chr22.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr22.txt -m ../rfmix4/Ref.map --chromosome=22 -o Rennell.chr22 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Santa-Cruz.chr1.vcf.gz -r ../rfmix4/bisnp.chr1.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr1.txt -m ../rfmix4/Ref.map --chromosome=1 -o Santa-Cruz.chr1 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Santa-Cruz.chr2.vcf.gz -r ../rfmix4/bisnp.chr2.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr2.txt -m ../rfmix4/Ref.map --chromosome=2 -o Santa-Cruz.chr2 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Santa-Cruz.chr3.vcf.gz -r ../rfmix4/bisnp.chr3.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr3.txt -m ../rfmix4/Ref.map --chromosome=3 -o Santa-Cruz.chr3 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Santa-Cruz.chr4.vcf.gz -r ../rfmix4/bisnp.chr4.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr4.txt -m ../rfmix4/Ref.map --chromosome=4 -o Santa-Cruz.chr4 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Santa-Cruz.chr5.vcf.gz -r ../rfmix4/bisnp.chr5.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr5.txt -m ../rfmix4/Ref.map --chromosome=5 -o Santa-Cruz.chr5 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Santa-Cruz.chr6.vcf.gz -r ../rfmix4/bisnp.chr6.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr6.txt -m ../rfmix4/Ref.map --chromosome=6 -o Santa-Cruz.chr6 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Santa-Cruz.chr7.vcf.gz -r ../rfmix4/bisnp.chr7.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr7.txt -m ../rfmix4/Ref.map --chromosome=7 -o Santa-Cruz.chr7 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Santa-Cruz.chr8.vcf.gz -r ../rfmix4/bisnp.chr8.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr8.txt -m ../rfmix4/Ref.map --chromosome=8 -o Santa-Cruz.chr8 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Santa-Cruz.chr9.vcf.gz -r ../rfmix4/bisnp.chr9.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr9.txt -m ../rfmix4/Ref.map --chromosome=9 -o Santa-Cruz.chr9 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Santa-Cruz.chr10.vcf.gz -r ../rfmix4/bisnp.chr10.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr10.txt -m ../rfmix4/Ref.map --chromosome=10 -o Santa-Cruz.chr10 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Santa-Cruz.chr11.vcf.gz -r ../rfmix4/bisnp.chr11.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr11.txt -m ../rfmix4/Ref.map --chromosome=11 -o Santa-Cruz.chr11 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Santa-Cruz.chr12.vcf.gz -r ../rfmix4/bisnp.chr12.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr12.txt -m ../rfmix4/Ref.map --chromosome=12 -o Santa-Cruz.chr12 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Santa-Cruz.chr13.vcf.gz -r ../rfmix4/bisnp.chr13.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr13.txt -m ../rfmix4/Ref.map --chromosome=13 -o Santa-Cruz.chr13 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Santa-Cruz.chr14.vcf.gz -r ../rfmix4/bisnp.chr14.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr14.txt -m ../rfmix4/Ref.map --chromosome=14 -o Santa-Cruz.chr14 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Santa-Cruz.chr15.vcf.gz -r ../rfmix4/bisnp.chr15.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr15.txt -m ../rfmix4/Ref.map --chromosome=15 -o Santa-Cruz.chr15 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Santa-Cruz.chr16.vcf.gz -r ../rfmix4/bisnp.chr16.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr16.txt -m ../rfmix4/Ref.map --chromosome=16 -o Santa-Cruz.chr16 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Santa-Cruz.chr17.vcf.gz -r ../rfmix4/bisnp.chr17.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr17.txt -m ../rfmix4/Ref.map --chromosome=17 -o Santa-Cruz.chr17 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Santa-Cruz.chr18.vcf.gz -r ../rfmix4/bisnp.chr18.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr18.txt -m ../rfmix4/Ref.map --chromosome=18 -o Santa-Cruz.chr18 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Santa-Cruz.chr19.vcf.gz -r ../rfmix4/bisnp.chr19.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr19.txt -m ../rfmix4/Ref.map --chromosome=19 -o Santa-Cruz.chr19 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Santa-Cruz.chr20.vcf.gz -r ../rfmix4/bisnp.chr20.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr20.txt -m ../rfmix4/Ref.map --chromosome=20 -o Santa-Cruz.chr20 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Santa-Cruz.chr21.vcf.gz -r ../rfmix4/bisnp.chr21.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr21.txt -m ../rfmix4/Ref.map --chromosome=21 -o Santa-Cruz.chr21 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Santa-Cruz.chr22.vcf.gz -r ../rfmix4/bisnp.chr22.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr22.txt -m ../rfmix4/Ref.map --chromosome=22 -o Santa-Cruz.chr22 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Saposa.chr1.vcf.gz -r ../rfmix4/bisnp.chr1.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr1.txt -m ../rfmix4/Ref.map --chromosome=1 -o Saposa.chr1 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Saposa.chr2.vcf.gz -r ../rfmix4/bisnp.chr2.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr2.txt -m ../rfmix4/Ref.map --chromosome=2 -o Saposa.chr2 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Saposa.chr3.vcf.gz -r ../rfmix4/bisnp.chr3.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr3.txt -m ../rfmix4/Ref.map --chromosome=3 -o Saposa.chr3 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Saposa.chr4.vcf.gz -r ../rfmix4/bisnp.chr4.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr4.txt -m ../rfmix4/Ref.map --chromosome=4 -o Saposa.chr4 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Saposa.chr5.vcf.gz -r ../rfmix4/bisnp.chr5.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr5.txt -m ../rfmix4/Ref.map --chromosome=5 -o Saposa.chr5 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Saposa.chr6.vcf.gz -r ../rfmix4/bisnp.chr6.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr6.txt -m ../rfmix4/Ref.map --chromosome=6 -o Saposa.chr6 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Saposa.chr7.vcf.gz -r ../rfmix4/bisnp.chr7.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr7.txt -m ../rfmix4/Ref.map --chromosome=7 -o Saposa.chr7 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Saposa.chr8.vcf.gz -r ../rfmix4/bisnp.chr8.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr8.txt -m ../rfmix4/Ref.map --chromosome=8 -o Saposa.chr8 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Saposa.chr9.vcf.gz -r ../rfmix4/bisnp.chr9.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr9.txt -m ../rfmix4/Ref.map --chromosome=9 -o Saposa.chr9 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Saposa.chr10.vcf.gz -r ../rfmix4/bisnp.chr10.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr10.txt -m ../rfmix4/Ref.map --chromosome=10 -o Saposa.chr10 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Saposa.chr11.vcf.gz -r ../rfmix4/bisnp.chr11.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr11.txt -m ../rfmix4/Ref.map --chromosome=11 -o Saposa.chr11 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Saposa.chr12.vcf.gz -r ../rfmix4/bisnp.chr12.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr12.txt -m ../rfmix4/Ref.map --chromosome=12 -o Saposa.chr12 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Saposa.chr13.vcf.gz -r ../rfmix4/bisnp.chr13.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr13.txt -m ../rfmix4/Ref.map --chromosome=13 -o Saposa.chr13 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Saposa.chr14.vcf.gz -r ../rfmix4/bisnp.chr14.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr14.txt -m ../rfmix4/Ref.map --chromosome=14 -o Saposa.chr14 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Saposa.chr15.vcf.gz -r ../rfmix4/bisnp.chr15.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr15.txt -m ../rfmix4/Ref.map --chromosome=15 -o Saposa.chr15 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Saposa.chr16.vcf.gz -r ../rfmix4/bisnp.chr16.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr16.txt -m ../rfmix4/Ref.map --chromosome=16 -o Saposa.chr16 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Saposa.chr17.vcf.gz -r ../rfmix4/bisnp.chr17.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr17.txt -m ../rfmix4/Ref.map --chromosome=17 -o Saposa.chr17 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Saposa.chr18.vcf.gz -r ../rfmix4/bisnp.chr18.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr18.txt -m ../rfmix4/Ref.map --chromosome=18 -o Saposa.chr18 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Saposa.chr19.vcf.gz -r ../rfmix4/bisnp.chr19.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr19.txt -m ../rfmix4/Ref.map --chromosome=19 -o Saposa.chr19 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Saposa.chr20.vcf.gz -r ../rfmix4/bisnp.chr20.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr20.txt -m ../rfmix4/Ref.map --chromosome=20 -o Saposa.chr20 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Saposa.chr21.vcf.gz -r ../rfmix4/bisnp.chr21.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr21.txt -m ../rfmix4/Ref.map --chromosome=21 -o Saposa.chr21 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Saposa.chr22.vcf.gz -r ../rfmix4/bisnp.chr22.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr22.txt -m ../rfmix4/Ref.map --chromosome=22 -o Saposa.chr22 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Sepik.chr1.vcf.gz -r ../rfmix4/bisnp.chr1.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr1.txt -m ../rfmix4/Ref.map --chromosome=1 -o Sepik.chr1 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Sepik.chr2.vcf.gz -r ../rfmix4/bisnp.chr2.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr2.txt -m ../rfmix4/Ref.map --chromosome=2 -o Sepik.chr2 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Sepik.chr3.vcf.gz -r ../rfmix4/bisnp.chr3.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr3.txt -m ../rfmix4/Ref.map --chromosome=3 -o Sepik.chr3 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Sepik.chr4.vcf.gz -r ../rfmix4/bisnp.chr4.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr4.txt -m ../rfmix4/Ref.map --chromosome=4 -o Sepik.chr4 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Sepik.chr5.vcf.gz -r ../rfmix4/bisnp.chr5.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr5.txt -m ../rfmix4/Ref.map --chromosome=5 -o Sepik.chr5 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Sepik.chr6.vcf.gz -r ../rfmix4/bisnp.chr6.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr6.txt -m ../rfmix4/Ref.map --chromosome=6 -o Sepik.chr6 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Sepik.chr7.vcf.gz -r ../rfmix4/bisnp.chr7.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr7.txt -m ../rfmix4/Ref.map --chromosome=7 -o Sepik.chr7 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Sepik.chr8.vcf.gz -r ../rfmix4/bisnp.chr8.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr8.txt -m ../rfmix4/Ref.map --chromosome=8 -o Sepik.chr8 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Sepik.chr9.vcf.gz -r ../rfmix4/bisnp.chr9.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr9.txt -m ../rfmix4/Ref.map --chromosome=9 -o Sepik.chr9 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Sepik.chr10.vcf.gz -r ../rfmix4/bisnp.chr10.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr10.txt -m ../rfmix4/Ref.map --chromosome=10 -o Sepik.chr10 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Sepik.chr11.vcf.gz -r ../rfmix4/bisnp.chr11.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr11.txt -m ../rfmix4/Ref.map --chromosome=11 -o Sepik.chr11 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Sepik.chr12.vcf.gz -r ../rfmix4/bisnp.chr12.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr12.txt -m ../rfmix4/Ref.map --chromosome=12 -o Sepik.chr12 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Sepik.chr13.vcf.gz -r ../rfmix4/bisnp.chr13.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr13.txt -m ../rfmix4/Ref.map --chromosome=13 -o Sepik.chr13 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Sepik.chr14.vcf.gz -r ../rfmix4/bisnp.chr14.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr14.txt -m ../rfmix4/Ref.map --chromosome=14 -o Sepik.chr14 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Sepik.chr15.vcf.gz -r ../rfmix4/bisnp.chr15.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr15.txt -m ../rfmix4/Ref.map --chromosome=15 -o Sepik.chr15 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Sepik.chr16.vcf.gz -r ../rfmix4/bisnp.chr16.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr16.txt -m ../rfmix4/Ref.map --chromosome=16 -o Sepik.chr16 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Sepik.chr17.vcf.gz -r ../rfmix4/bisnp.chr17.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr17.txt -m ../rfmix4/Ref.map --chromosome=17 -o Sepik.chr17 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Sepik.chr18.vcf.gz -r ../rfmix4/bisnp.chr18.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr18.txt -m ../rfmix4/Ref.map --chromosome=18 -o Sepik.chr18 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Sepik.chr19.vcf.gz -r ../rfmix4/bisnp.chr19.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr19.txt -m ../rfmix4/Ref.map --chromosome=19 -o Sepik.chr19 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Sepik.chr20.vcf.gz -r ../rfmix4/bisnp.chr20.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr20.txt -m ../rfmix4/Ref.map --chromosome=20 -o Sepik.chr20 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Sepik.chr21.vcf.gz -r ../rfmix4/bisnp.chr21.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr21.txt -m ../rfmix4/Ref.map --chromosome=21 -o Sepik.chr21 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Sepik.chr22.vcf.gz -r ../rfmix4/bisnp.chr22.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr22.txt -m ../rfmix4/Ref.map --chromosome=22 -o Sepik.chr22 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Tikopia.chr1.vcf.gz -r ../rfmix4/bisnp.chr1.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr1.txt -m ../rfmix4/Ref.map --chromosome=1 -o Tikopia.chr1 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Tikopia.chr2.vcf.gz -r ../rfmix4/bisnp.chr2.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr2.txt -m ../rfmix4/Ref.map --chromosome=2 -o Tikopia.chr2 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Tikopia.chr3.vcf.gz -r ../rfmix4/bisnp.chr3.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr3.txt -m ../rfmix4/Ref.map --chromosome=3 -o Tikopia.chr3 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Tikopia.chr4.vcf.gz -r ../rfmix4/bisnp.chr4.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr4.txt -m ../rfmix4/Ref.map --chromosome=4 -o Tikopia.chr4 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Tikopia.chr5.vcf.gz -r ../rfmix4/bisnp.chr5.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr5.txt -m ../rfmix4/Ref.map --chromosome=5 -o Tikopia.chr5 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Tikopia.chr6.vcf.gz -r ../rfmix4/bisnp.chr6.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr6.txt -m ../rfmix4/Ref.map --chromosome=6 -o Tikopia.chr6 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Tikopia.chr7.vcf.gz -r ../rfmix4/bisnp.chr7.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr7.txt -m ../rfmix4/Ref.map --chromosome=7 -o Tikopia.chr7 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Tikopia.chr8.vcf.gz -r ../rfmix4/bisnp.chr8.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr8.txt -m ../rfmix4/Ref.map --chromosome=8 -o Tikopia.chr8 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Tikopia.chr9.vcf.gz -r ../rfmix4/bisnp.chr9.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr9.txt -m ../rfmix4/Ref.map --chromosome=9 -o Tikopia.chr9 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Tikopia.chr10.vcf.gz -r ../rfmix4/bisnp.chr10.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr10.txt -m ../rfmix4/Ref.map --chromosome=10 -o Tikopia.chr10 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Tikopia.chr11.vcf.gz -r ../rfmix4/bisnp.chr11.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr11.txt -m ../rfmix4/Ref.map --chromosome=11 -o Tikopia.chr11 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Tikopia.chr12.vcf.gz -r ../rfmix4/bisnp.chr12.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr12.txt -m ../rfmix4/Ref.map --chromosome=12 -o Tikopia.chr12 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Tikopia.chr13.vcf.gz -r ../rfmix4/bisnp.chr13.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr13.txt -m ../rfmix4/Ref.map --chromosome=13 -o Tikopia.chr13 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Tikopia.chr14.vcf.gz -r ../rfmix4/bisnp.chr14.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr14.txt -m ../rfmix4/Ref.map --chromosome=14 -o Tikopia.chr14 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Tikopia.chr15.vcf.gz -r ../rfmix4/bisnp.chr15.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr15.txt -m ../rfmix4/Ref.map --chromosome=15 -o Tikopia.chr15 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Tikopia.chr16.vcf.gz -r ../rfmix4/bisnp.chr16.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr16.txt -m ../rfmix4/Ref.map --chromosome=16 -o Tikopia.chr16 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Tikopia.chr17.vcf.gz -r ../rfmix4/bisnp.chr17.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr17.txt -m ../rfmix4/Ref.map --chromosome=17 -o Tikopia.chr17 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Tikopia.chr18.vcf.gz -r ../rfmix4/bisnp.chr18.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr18.txt -m ../rfmix4/Ref.map --chromosome=18 -o Tikopia.chr18 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Tikopia.chr19.vcf.gz -r ../rfmix4/bisnp.chr19.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr19.txt -m ../rfmix4/Ref.map --chromosome=19 -o Tikopia.chr19 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Tikopia.chr20.vcf.gz -r ../rfmix4/bisnp.chr20.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr20.txt -m ../rfmix4/Ref.map --chromosome=20 -o Tikopia.chr20 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Tikopia.chr21.vcf.gz -r ../rfmix4/bisnp.chr21.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr21.txt -m ../rfmix4/Ref.map --chromosome=21 -o Tikopia.chr21 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Tikopia.chr22.vcf.gz -r ../rfmix4/bisnp.chr22.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr22.txt -m ../rfmix4/Ref.map --chromosome=22 -o Tikopia.chr22 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Vella-Lavella.chr1.vcf.gz -r ../rfmix4/bisnp.chr1.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr1.txt -m ../rfmix4/Ref.map --chromosome=1 -o Vella-Lavella.chr1 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Vella-Lavella.chr2.vcf.gz -r ../rfmix4/bisnp.chr2.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr2.txt -m ../rfmix4/Ref.map --chromosome=2 -o Vella-Lavella.chr2 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Vella-Lavella.chr3.vcf.gz -r ../rfmix4/bisnp.chr3.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr3.txt -m ../rfmix4/Ref.map --chromosome=3 -o Vella-Lavella.chr3 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Vella-Lavella.chr4.vcf.gz -r ../rfmix4/bisnp.chr4.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr4.txt -m ../rfmix4/Ref.map --chromosome=4 -o Vella-Lavella.chr4 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Vella-Lavella.chr5.vcf.gz -r ../rfmix4/bisnp.chr5.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr5.txt -m ../rfmix4/Ref.map --chromosome=5 -o Vella-Lavella.chr5 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Vella-Lavella.chr6.vcf.gz -r ../rfmix4/bisnp.chr6.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr6.txt -m ../rfmix4/Ref.map --chromosome=6 -o Vella-Lavella.chr6 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Vella-Lavella.chr7.vcf.gz -r ../rfmix4/bisnp.chr7.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr7.txt -m ../rfmix4/Ref.map --chromosome=7 -o Vella-Lavella.chr7 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Vella-Lavella.chr8.vcf.gz -r ../rfmix4/bisnp.chr8.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr8.txt -m ../rfmix4/Ref.map --chromosome=8 -o Vella-Lavella.chr8 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Vella-Lavella.chr9.vcf.gz -r ../rfmix4/bisnp.chr9.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr9.txt -m ../rfmix4/Ref.map --chromosome=9 -o Vella-Lavella.chr9 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Vella-Lavella.chr10.vcf.gz -r ../rfmix4/bisnp.chr10.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr10.txt -m ../rfmix4/Ref.map --chromosome=10 -o Vella-Lavella.chr10 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Vella-Lavella.chr11.vcf.gz -r ../rfmix4/bisnp.chr11.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr11.txt -m ../rfmix4/Ref.map --chromosome=11 -o Vella-Lavella.chr11 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Vella-Lavella.chr12.vcf.gz -r ../rfmix4/bisnp.chr12.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr12.txt -m ../rfmix4/Ref.map --chromosome=12 -o Vella-Lavella.chr12 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Vella-Lavella.chr13.vcf.gz -r ../rfmix4/bisnp.chr13.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr13.txt -m ../rfmix4/Ref.map --chromosome=13 -o Vella-Lavella.chr13 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Vella-Lavella.chr14.vcf.gz -r ../rfmix4/bisnp.chr14.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr14.txt -m ../rfmix4/Ref.map --chromosome=14 -o Vella-Lavella.chr14 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Vella-Lavella.chr15.vcf.gz -r ../rfmix4/bisnp.chr15.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr15.txt -m ../rfmix4/Ref.map --chromosome=15 -o Vella-Lavella.chr15 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Vella-Lavella.chr16.vcf.gz -r ../rfmix4/bisnp.chr16.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr16.txt -m ../rfmix4/Ref.map --chromosome=16 -o Vella-Lavella.chr16 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Vella-Lavella.chr17.vcf.gz -r ../rfmix4/bisnp.chr17.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr17.txt -m ../rfmix4/Ref.map --chromosome=17 -o Vella-Lavella.chr17 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Vella-Lavella.chr18.vcf.gz -r ../rfmix4/bisnp.chr18.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr18.txt -m ../rfmix4/Ref.map --chromosome=18 -o Vella-Lavella.chr18 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Vella-Lavella.chr19.vcf.gz -r ../rfmix4/bisnp.chr19.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr19.txt -m ../rfmix4/Ref.map --chromosome=19 -o Vella-Lavella.chr19 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Vella-Lavella.chr20.vcf.gz -r ../rfmix4/bisnp.chr20.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr20.txt -m ../rfmix4/Ref.map --chromosome=20 -o Vella-Lavella.chr20 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Vella-Lavella.chr21.vcf.gz -r ../rfmix4/bisnp.chr21.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr21.txt -m ../rfmix4/Ref.map --chromosome=21 -o Vella-Lavella.chr21 -s 0.03 --n-threads=4
rfmix -f ../rfmix4/Vella-Lavella.chr22.vcf.gz -r ../rfmix4/bisnp.chr22.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr22.txt -m ../rfmix4/Ref.map --chromosome=22 -o Vella-Lavella.chr22 -s 0.03 --n-threads=4
