rfmix -f ../rfmix4/Agta.chr1.vcf.gz -r ../rfmix4/bisnp.chr1.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr1.txt -m ../rfmix4/Ref.map --chromosome=1 -o Agta.chr1 -s 0.03 --n-threads=8
rfmix -f ../rfmix4/Agta.chr2.vcf.gz -r ../rfmix4/bisnp.chr2.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr2.txt -m ../rfmix4/Ref.map --chromosome=2 -o Agta.chr2 -s 0.03 --n-threads=8
rfmix -f ../rfmix4/Agta.chr3.vcf.gz -r ../rfmix4/bisnp.chr3.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr3.txt -m ../rfmix4/Ref.map --chromosome=3 -o Agta.chr3 -s 0.03 --n-threads=8
rfmix -f ../rfmix4/Agta.chr4.vcf.gz -r ../rfmix4/bisnp.chr4.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr4.txt -m ../rfmix4/Ref.map --chromosome=4 -o Agta.chr4 -s 0.03 --n-threads=8
rfmix -f ../rfmix4/Agta.chr5.vcf.gz -r ../rfmix4/bisnp.chr5.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr5.txt -m ../rfmix4/Ref.map --chromosome=5 -o Agta.chr5 -s 0.03 --n-threads=8
rfmix -f ../rfmix4/Agta.chr6.vcf.gz -r ../rfmix4/bisnp.chr6.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr6.txt -m ../rfmix4/Ref.map --chromosome=6 -o Agta.chr6 -s 0.03 --n-threads=8
rfmix -f ../rfmix4/Agta.chr7.vcf.gz -r ../rfmix4/bisnp.chr7.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr7.txt -m ../rfmix4/Ref.map --chromosome=7 -o Agta.chr7 -s 0.03 --n-threads=8
rfmix -f ../rfmix4/Agta.chr8.vcf.gz -r ../rfmix4/bisnp.chr8.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr8.txt -m ../rfmix4/Ref.map --chromosome=8 -o Agta.chr8 -s 0.03 --n-threads=8
rfmix -f ../rfmix4/Agta.chr9.vcf.gz -r ../rfmix4/bisnp.chr9.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr9.txt -m ../rfmix4/Ref.map --chromosome=9 -o Agta.chr9 -s 0.03 --n-threads=8
rfmix -f ../rfmix4/Agta.chr10.vcf.gz -r ../rfmix4/bisnp.chr10.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr10.txt -m ../rfmix4/Ref.map --chromosome=10 -o Agta.chr10 -s 0.03 --n-threads=8
rfmix -f ../rfmix4/Agta.chr11.vcf.gz -r ../rfmix4/bisnp.chr11.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr11.txt -m ../rfmix4/Ref.map --chromosome=11 -o Agta.chr11 -s 0.03 --n-threads=8
rfmix -f ../rfmix4/Agta.chr12.vcf.gz -r ../rfmix4/bisnp.chr12.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr12.txt -m ../rfmix4/Ref.map --chromosome=12 -o Agta.chr12 -s 0.03 --n-threads=8
rfmix -f ../rfmix4/Agta.chr13.vcf.gz -r ../rfmix4/bisnp.chr13.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr13.txt -m ../rfmix4/Ref.map --chromosome=13 -o Agta.chr13 -s 0.03 --n-threads=8
rfmix -f ../rfmix4/Agta.chr14.vcf.gz -r ../rfmix4/bisnp.chr14.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr14.txt -m ../rfmix4/Ref.map --chromosome=14 -o Agta.chr14 -s 0.03 --n-threads=8
rfmix -f ../rfmix4/Agta.chr15.vcf.gz -r ../rfmix4/bisnp.chr15.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr15.txt -m ../rfmix4/Ref.map --chromosome=15 -o Agta.chr15 -s 0.03 --n-threads=8
rfmix -f ../rfmix4/Agta.chr16.vcf.gz -r ../rfmix4/bisnp.chr16.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr16.txt -m ../rfmix4/Ref.map --chromosome=16 -o Agta.chr16 -s 0.03 --n-threads=8
rfmix -f ../rfmix4/Agta.chr17.vcf.gz -r ../rfmix4/bisnp.chr17.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr17.txt -m ../rfmix4/Ref.map --chromosome=17 -o Agta.chr17 -s 0.03 --n-threads=8
rfmix -f ../rfmix4/Agta.chr18.vcf.gz -r ../rfmix4/bisnp.chr18.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr18.txt -m ../rfmix4/Ref.map --chromosome=18 -o Agta.chr18 -s 0.03 --n-threads=8
rfmix -f ../rfmix4/Agta.chr19.vcf.gz -r ../rfmix4/bisnp.chr19.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr19.txt -m ../rfmix4/Ref.map --chromosome=19 -o Agta.chr19 -s 0.03 --n-threads=8
rfmix -f ../rfmix4/Agta.chr20.vcf.gz -r ../rfmix4/bisnp.chr20.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr20.txt -m ../rfmix4/Ref.map --chromosome=20 -o Agta.chr20 -s 0.03 --n-threads=8
rfmix -f ../rfmix4/Agta.chr21.vcf.gz -r ../rfmix4/bisnp.chr21.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr21.txt -m ../rfmix4/Ref.map --chromosome=21 -o Agta.chr21 -s 0.03 --n-threads=8
rfmix -f ../rfmix4/Agta.chr22.vcf.gz -r ../rfmix4/bisnp.chr22.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr22.txt -m ../rfmix4/Ref.map --chromosome=22 -o Agta.chr22 -s 0.03 --n-threads=8
rfmix -f ../rfmix4/Cebuano.chr1.vcf.gz -r ../rfmix4/bisnp.chr1.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr1.txt -m ../rfmix4/Ref.map --chromosome=1 -o Cebuano.chr1 -s 0.03 --n-threads=8
rfmix -f ../rfmix4/Cebuano.chr2.vcf.gz -r ../rfmix4/bisnp.chr2.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr2.txt -m ../rfmix4/Ref.map --chromosome=2 -o Cebuano.chr2 -s 0.03 --n-threads=8
rfmix -f ../rfmix4/Cebuano.chr3.vcf.gz -r ../rfmix4/bisnp.chr3.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr3.txt -m ../rfmix4/Ref.map --chromosome=3 -o Cebuano.chr3 -s 0.03 --n-threads=8
rfmix -f ../rfmix4/Cebuano.chr4.vcf.gz -r ../rfmix4/bisnp.chr4.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr4.txt -m ../rfmix4/Ref.map --chromosome=4 -o Cebuano.chr4 -s 0.03 --n-threads=8
rfmix -f ../rfmix4/Cebuano.chr5.vcf.gz -r ../rfmix4/bisnp.chr5.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr5.txt -m ../rfmix4/Ref.map --chromosome=5 -o Cebuano.chr5 -s 0.03 --n-threads=8
rfmix -f ../rfmix4/Cebuano.chr6.vcf.gz -r ../rfmix4/bisnp.chr6.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr6.txt -m ../rfmix4/Ref.map --chromosome=6 -o Cebuano.chr6 -s 0.03 --n-threads=8
rfmix -f ../rfmix4/Cebuano.chr7.vcf.gz -r ../rfmix4/bisnp.chr7.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr7.txt -m ../rfmix4/Ref.map --chromosome=7 -o Cebuano.chr7 -s 0.03 --n-threads=8
rfmix -f ../rfmix4/Cebuano.chr8.vcf.gz -r ../rfmix4/bisnp.chr8.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr8.txt -m ../rfmix4/Ref.map --chromosome=8 -o Cebuano.chr8 -s 0.03 --n-threads=8
rfmix -f ../rfmix4/Cebuano.chr9.vcf.gz -r ../rfmix4/bisnp.chr9.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr9.txt -m ../rfmix4/Ref.map --chromosome=9 -o Cebuano.chr9 -s 0.03 --n-threads=8
rfmix -f ../rfmix4/Cebuano.chr10.vcf.gz -r ../rfmix4/bisnp.chr10.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr10.txt -m ../rfmix4/Ref.map --chromosome=10 -o Cebuano.chr10 -s 0.03 --n-threads=8
rfmix -f ../rfmix4/Cebuano.chr11.vcf.gz -r ../rfmix4/bisnp.chr11.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr11.txt -m ../rfmix4/Ref.map --chromosome=11 -o Cebuano.chr11 -s 0.03 --n-threads=8
rfmix -f ../rfmix4/Cebuano.chr12.vcf.gz -r ../rfmix4/bisnp.chr12.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr12.txt -m ../rfmix4/Ref.map --chromosome=12 -o Cebuano.chr12 -s 0.03 --n-threads=8
rfmix -f ../rfmix4/Cebuano.chr13.vcf.gz -r ../rfmix4/bisnp.chr13.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr13.txt -m ../rfmix4/Ref.map --chromosome=13 -o Cebuano.chr13 -s 0.03 --n-threads=8
rfmix -f ../rfmix4/Cebuano.chr14.vcf.gz -r ../rfmix4/bisnp.chr14.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr14.txt -m ../rfmix4/Ref.map --chromosome=14 -o Cebuano.chr14 -s 0.03 --n-threads=8
rfmix -f ../rfmix4/Cebuano.chr15.vcf.gz -r ../rfmix4/bisnp.chr15.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr15.txt -m ../rfmix4/Ref.map --chromosome=15 -o Cebuano.chr15 -s 0.03 --n-threads=8
rfmix -f ../rfmix4/Cebuano.chr16.vcf.gz -r ../rfmix4/bisnp.chr16.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr16.txt -m ../rfmix4/Ref.map --chromosome=16 -o Cebuano.chr16 -s 0.03 --n-threads=8
rfmix -f ../rfmix4/Cebuano.chr17.vcf.gz -r ../rfmix4/bisnp.chr17.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr17.txt -m ../rfmix4/Ref.map --chromosome=17 -o Cebuano.chr17 -s 0.03 --n-threads=8
rfmix -f ../rfmix4/Cebuano.chr18.vcf.gz -r ../rfmix4/bisnp.chr18.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr18.txt -m ../rfmix4/Ref.map --chromosome=18 -o Cebuano.chr18 -s 0.03 --n-threads=8
rfmix -f ../rfmix4/Cebuano.chr19.vcf.gz -r ../rfmix4/bisnp.chr19.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr19.txt -m ../rfmix4/Ref.map --chromosome=19 -o Cebuano.chr19 -s 0.03 --n-threads=8
rfmix -f ../rfmix4/Cebuano.chr20.vcf.gz -r ../rfmix4/bisnp.chr20.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr20.txt -m ../rfmix4/Ref.map --chromosome=20 -o Cebuano.chr20 -s 0.03 --n-threads=8
rfmix -f ../rfmix4/Cebuano.chr21.vcf.gz -r ../rfmix4/bisnp.chr21.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr21.txt -m ../rfmix4/Ref.map --chromosome=21 -o Cebuano.chr21 -s 0.03 --n-threads=8
rfmix -f ../rfmix4/Cebuano.chr22.vcf.gz -r ../rfmix4/bisnp.chr22.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr22.txt -m ../rfmix4/Ref.map --chromosome=22 -o Cebuano.chr22 -s 0.03 --n-threads=8
rfmix -f ../rfmix4/Rampasasa.chr1.vcf.gz -r ../rfmix4/bisnp.chr1.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr1.txt -m ../rfmix4/Ref.map --chromosome=1 -o Rampasasa.chr1 -s 0.03 --n-threads=8
rfmix -f ../rfmix4/Rampasasa.chr2.vcf.gz -r ../rfmix4/bisnp.chr2.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr2.txt -m ../rfmix4/Ref.map --chromosome=2 -o Rampasasa.chr2 -s 0.03 --n-threads=8
rfmix -f ../rfmix4/Rampasasa.chr3.vcf.gz -r ../rfmix4/bisnp.chr3.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr3.txt -m ../rfmix4/Ref.map --chromosome=3 -o Rampasasa.chr3 -s 0.03 --n-threads=8
rfmix -f ../rfmix4/Rampasasa.chr4.vcf.gz -r ../rfmix4/bisnp.chr4.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr4.txt -m ../rfmix4/Ref.map --chromosome=4 -o Rampasasa.chr4 -s 0.03 --n-threads=8
rfmix -f ../rfmix4/Rampasasa.chr5.vcf.gz -r ../rfmix4/bisnp.chr5.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr5.txt -m ../rfmix4/Ref.map --chromosome=5 -o Rampasasa.chr5 -s 0.03 --n-threads=8
rfmix -f ../rfmix4/Rampasasa.chr6.vcf.gz -r ../rfmix4/bisnp.chr6.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr6.txt -m ../rfmix4/Ref.map --chromosome=6 -o Rampasasa.chr6 -s 0.03 --n-threads=8
rfmix -f ../rfmix4/Rampasasa.chr7.vcf.gz -r ../rfmix4/bisnp.chr7.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr7.txt -m ../rfmix4/Ref.map --chromosome=7 -o Rampasasa.chr7 -s 0.03 --n-threads=8
rfmix -f ../rfmix4/Rampasasa.chr8.vcf.gz -r ../rfmix4/bisnp.chr8.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr8.txt -m ../rfmix4/Ref.map --chromosome=8 -o Rampasasa.chr8 -s 0.03 --n-threads=8
rfmix -f ../rfmix4/Rampasasa.chr9.vcf.gz -r ../rfmix4/bisnp.chr9.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr9.txt -m ../rfmix4/Ref.map --chromosome=9 -o Rampasasa.chr9 -s 0.03 --n-threads=8
rfmix -f ../rfmix4/Rampasasa.chr10.vcf.gz -r ../rfmix4/bisnp.chr10.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr10.txt -m ../rfmix4/Ref.map --chromosome=10 -o Rampasasa.chr10 -s 0.03 --n-threads=8
rfmix -f ../rfmix4/Rampasasa.chr11.vcf.gz -r ../rfmix4/bisnp.chr11.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr11.txt -m ../rfmix4/Ref.map --chromosome=11 -o Rampasasa.chr11 -s 0.03 --n-threads=8
rfmix -f ../rfmix4/Rampasasa.chr12.vcf.gz -r ../rfmix4/bisnp.chr12.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr12.txt -m ../rfmix4/Ref.map --chromosome=12 -o Rampasasa.chr12 -s 0.03 --n-threads=8
rfmix -f ../rfmix4/Rampasasa.chr13.vcf.gz -r ../rfmix4/bisnp.chr13.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr13.txt -m ../rfmix4/Ref.map --chromosome=13 -o Rampasasa.chr13 -s 0.03 --n-threads=8
rfmix -f ../rfmix4/Rampasasa.chr14.vcf.gz -r ../rfmix4/bisnp.chr14.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr14.txt -m ../rfmix4/Ref.map --chromosome=14 -o Rampasasa.chr14 -s 0.03 --n-threads=8
rfmix -f ../rfmix4/Rampasasa.chr15.vcf.gz -r ../rfmix4/bisnp.chr15.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr15.txt -m ../rfmix4/Ref.map --chromosome=15 -o Rampasasa.chr15 -s 0.03 --n-threads=8
rfmix -f ../rfmix4/Rampasasa.chr16.vcf.gz -r ../rfmix4/bisnp.chr16.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr16.txt -m ../rfmix4/Ref.map --chromosome=16 -o Rampasasa.chr16 -s 0.03 --n-threads=8
rfmix -f ../rfmix4/Rampasasa.chr17.vcf.gz -r ../rfmix4/bisnp.chr17.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr17.txt -m ../rfmix4/Ref.map --chromosome=17 -o Rampasasa.chr17 -s 0.03 --n-threads=8
rfmix -f ../rfmix4/Rampasasa.chr18.vcf.gz -r ../rfmix4/bisnp.chr18.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr18.txt -m ../rfmix4/Ref.map --chromosome=18 -o Rampasasa.chr18 -s 0.03 --n-threads=8
rfmix -f ../rfmix4/Rampasasa.chr19.vcf.gz -r ../rfmix4/bisnp.chr19.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr19.txt -m ../rfmix4/Ref.map --chromosome=19 -o Rampasasa.chr19 -s 0.03 --n-threads=8
rfmix -f ../rfmix4/Rampasasa.chr20.vcf.gz -r ../rfmix4/bisnp.chr20.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr20.txt -m ../rfmix4/Ref.map --chromosome=20 -o Rampasasa.chr20 -s 0.03 --n-threads=8
rfmix -f ../rfmix4/Rampasasa.chr21.vcf.gz -r ../rfmix4/bisnp.chr21.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr21.txt -m ../rfmix4/Ref.map --chromosome=21 -o Rampasasa.chr21 -s 0.03 --n-threads=8
rfmix -f ../rfmix4/Rampasasa.chr22.vcf.gz -r ../rfmix4/bisnp.chr22.vcf.gz -g ../rfmix4/genetic_map_GRCh37_chr22.txt -m ../rfmix4/Ref.map --chromosome=22 -o Rampasasa.chr22 -s 0.03 --n-threads=8
